// Generated by gencs from visualization_msgs/MarkerArray.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.visualization_msgs;

namespace SIGVerse.RosBridge 
{
	namespace visualization_msgs 
	{
		[System.Serializable]
		public class MarkerArray : RosMessage
		{
			public System.Collections.Generic.List<visualization_msgs.Marker>  markers;


			public MarkerArray()
			{
				this.markers = new System.Collections.Generic.List<visualization_msgs.Marker>();
			}

			public MarkerArray(System.Collections.Generic.List<visualization_msgs.Marker>  markers)
			{
				this.markers = markers;
			}

			new public static string GetMessageType()
			{
				return "visualization_msgs/MarkerArray";
			}

			new public static string GetMD5Hash()
			{
				return "d155b9ce5188fbaf89745847fd5882d7";
			}
		} // class MarkerArray
	} // namespace visualization_msgs
} // namespace SIGVerse.ROSBridge

