// Generated by gencs from visualization_msgs/Marker.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs;
using SIGVerse.RosBridge.geometry_msgs;

namespace SIGVerse.RosBridge 
{
	namespace visualization_msgs 
	{
		[System.Serializable]
		public class Marker : RosMessage
		{
			public std_msgs.Header header;
			public string ns;
			public System.Int32 id;
			public System.Int32 type;
			public System.Int32 action;
			public geometry_msgs.Pose pose;
			public UnityEngine.Vector3 scale;
			public std_msgs.ColorRGBA color;
			public SIGVerse.RosBridge.msg_helpers.Duration lifetime;
			public bool frame_locked;
			public System.Collections.Generic.List<UnityEngine.Vector3>  points;
			public System.Collections.Generic.List<std_msgs.ColorRGBA>  colors;
			public string text;
			public string mesh_resource;
			public bool mesh_use_embedded_materials;

			public const byte ARROW = 0;
			public const byte CUBE = 1;
			public const byte SPHERE = 2;
			public const byte CYLINDER = 3;
			public const byte LINE_STRIP = 4;
			public const byte LINE_LIST = 5;
			public const byte CUBE_LIST = 6;
			public const byte SPHERE_LIST = 7;
			public const byte POINTS = 8;
			public const byte TEXT_VIEW_FACING = 9;
			public const byte MESH_RESOURCE = 10;
			public const byte TRIANGLE_LIST = 11;
			public const byte ADD = 0;
			public const byte MODIFY = 0;
			public const byte DELETE = 2;
			public const byte DELETEALL = 3;

			public Marker()
			{
				this.header = new std_msgs.Header();
				this.ns = "";
				this.id = 0;
				this.type = 0;
				this.action = 0;
				this.pose = new geometry_msgs.Pose();
				this.scale = new UnityEngine.Vector3();
				this.color = new std_msgs.ColorRGBA();
				this.lifetime = new SIGVerse.RosBridge.msg_helpers.Duration();
				this.frame_locked = false;
				this.points = new System.Collections.Generic.List<UnityEngine.Vector3>();
				this.colors = new System.Collections.Generic.List<std_msgs.ColorRGBA>();
				this.text = "";
				this.mesh_resource = "";
				this.mesh_use_embedded_materials = false;
			}

			public Marker(std_msgs.Header header, string ns, System.Int32 id, System.Int32 type, System.Int32 action, geometry_msgs.Pose pose, UnityEngine.Vector3 scale, std_msgs.ColorRGBA color, SIGVerse.RosBridge.msg_helpers.Duration lifetime, bool frame_locked, System.Collections.Generic.List<UnityEngine.Vector3>  points, System.Collections.Generic.List<std_msgs.ColorRGBA>  colors, string text, string mesh_resource, bool mesh_use_embedded_materials)
			{
				this.header = header;
				this.ns = ns;
				this.id = id;
				this.type = type;
				this.action = action;
				this.pose = pose;
				this.scale = scale;
				this.color = color;
				this.lifetime = lifetime;
				this.frame_locked = frame_locked;
				this.points = points;
				this.colors = colors;
				this.text = text;
				this.mesh_resource = mesh_resource;
				this.mesh_use_embedded_materials = mesh_use_embedded_materials;
			}

			new public static string GetMessageType()
			{
				return "visualization_msgs/Marker";
			}

			new public static string GetMD5Hash()
			{
				return "4048c9de2a16f4ae8e0538085ebf1b97";
			}
		} // class Marker
	} // namespace visualization_msgs
} // namespace SIGVerse.ROSBridge

