// Generated by gencs from visualization_msgs/MenuEntry.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace visualization_msgs 
	{
		[System.Serializable]
		public class MenuEntry : RosMessage
		{
			public System.UInt32 id;
			public System.UInt32 parent_id;
			public string title;
			public string command;
			public byte command_type;

			public const byte FEEDBACK = 0;
			public const byte ROSRUN = 1;
			public const byte ROSLAUNCH = 2;

			public MenuEntry()
			{
				this.id = 0;
				this.parent_id = 0;
				this.title = "";
				this.command = "";
				this.command_type = 0;
			}

			public MenuEntry(System.UInt32 id, System.UInt32 parent_id, string title, string command, byte command_type)
			{
				this.id = id;
				this.parent_id = parent_id;
				this.title = title;
				this.command = command;
				this.command_type = command_type;
			}

			new public static string GetMessageType()
			{
				return "visualization_msgs/MenuEntry";
			}

			new public static string GetMD5Hash()
			{
				return "b90ec63024573de83b57aa93eb39be2d";
			}
		} // class MenuEntry
	} // namespace visualization_msgs
} // namespace SIGVerse.ROSBridge

