// Generated by gencs from diagnostic_msgs/AddDiagnostics.srv
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace diagnostic_msgs 
	{
		[System.Serializable]
		public class AddDiagnosticsResponse : ServiceResponse
		{
			public bool success;
			public string message;


			public AddDiagnosticsResponse()
			{
				this.success = false;
				this.message = "";
			}

			public AddDiagnosticsResponse(bool success, string message)
			{
				this.success = success;
				this.message = message;
			}

			new public static string GetMessageType()
			{
				return "diagnostic_msgs/AddDiagnosticsResponse";
			}

			new public static string GetMD5Hash()
			{
				return "937c9679a518e3a18d831e57125ea522";
			}
		} // class AddDiagnosticsResponse
	} // namespace diagnostic_msgs
} // namespace SIGVerse.ROSBridge

