// Generated by gencs from diagnostic_msgs/KeyValue.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace diagnostic_msgs 
	{
		[System.Serializable]
		public class KeyValue : RosMessage
		{
			public string key;
			public string value;


			public KeyValue()
			{
				this.key = "";
				this.value = "";
			}

			public KeyValue(string key, string value)
			{
				this.key = key;
				this.value = value;
			}

			new public static string GetMessageType()
			{
				return "diagnostic_msgs/KeyValue";
			}

			new public static string GetMD5Hash()
			{
				return "cf57fdc6617a881a88c16e768132149c";
			}
		} // class KeyValue
	} // namespace diagnostic_msgs
} // namespace SIGVerse.ROSBridge

