// Generated by gencs from nav_msgs/msg/Goals.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs.msg;
using SIGVerse.RosBridge.geometry_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace nav_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class Goals : RosMessage
			{
				public std_msgs.msg.Header header;
				public System.Collections.Generic.List<geometry_msgs.msg.PoseStamped>  goals;


				public Goals()
				{
					this.header = new std_msgs.msg.Header();
					this.goals = new System.Collections.Generic.List<geometry_msgs.msg.PoseStamped>();
				}

				public Goals(std_msgs.msg.Header header, System.Collections.Generic.List<geometry_msgs.msg.PoseStamped>  goals)
				{
					this.header = header;
					this.goals = goals;
				}

				new public static string GetMessageType()
				{
					return "nav_msgs/msg/Goals";
				}

			} // class Goals
		} // namespace msg
	} // namespace nav_msgs
} // namespace SIGVerse.RosBridge
