// Generated by gencs from nav_msgs/msg/MapMetaData.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.builtin_interfaces.msg;
using SIGVerse.RosBridge.geometry_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace nav_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class MapMetaData : RosMessage
			{
				public builtin_interfaces.msg.Time map_load_time;
				public float resolution;
				public System.UInt32 width;
				public System.UInt32 height;
				public geometry_msgs.msg.Pose origin;


				public MapMetaData()
				{
					this.map_load_time = new builtin_interfaces.msg.Time();
					this.resolution = 0.0f;
					this.width = 0;
					this.height = 0;
					this.origin = new geometry_msgs.msg.Pose();
				}

				public MapMetaData(builtin_interfaces.msg.Time map_load_time, float resolution, System.UInt32 width, System.UInt32 height, geometry_msgs.msg.Pose origin)
				{
					this.map_load_time = map_load_time;
					this.resolution = resolution;
					this.width = width;
					this.height = height;
					this.origin = origin;
				}

				new public static string GetMessageType()
				{
					return "nav_msgs/msg/MapMetaData";
				}

			} // class MapMetaData
		} // namespace msg
	} // namespace nav_msgs
} // namespace SIGVerse.RosBridge
