// Generated by gencs from nav_msgs/msg/OccupancyGrid.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs.msg;
using SIGVerse.RosBridge.nav_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace nav_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class OccupancyGrid : RosMessage
			{
				public std_msgs.msg.Header header;
				public nav_msgs.msg.MapMetaData info;
				public System.Collections.Generic.List<sbyte>  data;


				public OccupancyGrid()
				{
					this.header = new std_msgs.msg.Header();
					this.info = new nav_msgs.msg.MapMetaData();
					this.data = new System.Collections.Generic.List<sbyte>();
				}

				public OccupancyGrid(std_msgs.msg.Header header, nav_msgs.msg.MapMetaData info, System.Collections.Generic.List<sbyte>  data)
				{
					this.header = header;
					this.info = info;
					this.data = data;
				}

				new public static string GetMessageType()
				{
					return "nav_msgs/msg/OccupancyGrid";
				}

			} // class OccupancyGrid
		} // namespace msg
	} // namespace nav_msgs
} // namespace SIGVerse.RosBridge
