// Generated by gencs from nav_msgs/msg/Odometry.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs.msg;
using SIGVerse.RosBridge.geometry_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace nav_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class Odometry : RosMessage
			{
				public std_msgs.msg.Header header;
				public string child_frame_id;
				public geometry_msgs.msg.PoseWithCovariance pose;
				public geometry_msgs.msg.TwistWithCovariance twist;


				public Odometry()
				{
					this.header = new std_msgs.msg.Header();
					this.child_frame_id = "";
					this.pose = new geometry_msgs.msg.PoseWithCovariance();
					this.twist = new geometry_msgs.msg.TwistWithCovariance();
				}

				public Odometry(std_msgs.msg.Header header, string child_frame_id, geometry_msgs.msg.PoseWithCovariance pose, geometry_msgs.msg.TwistWithCovariance twist)
				{
					this.header = header;
					this.child_frame_id = child_frame_id;
					this.pose = pose;
					this.twist = twist;
				}

				new public static string GetMessageType()
				{
					return "nav_msgs/msg/Odometry";
				}

			} // class Odometry
		} // namespace msg
	} // namespace nav_msgs
} // namespace SIGVerse.RosBridge
