// Generated by gencs from nav_msgs/msg/Path.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs.msg;
using SIGVerse.RosBridge.geometry_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace nav_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class Path : RosMessage
			{
				public std_msgs.msg.Header header;
				public System.Collections.Generic.List<geometry_msgs.msg.PoseStamped>  poses;


				public Path()
				{
					this.header = new std_msgs.msg.Header();
					this.poses = new System.Collections.Generic.List<geometry_msgs.msg.PoseStamped>();
				}

				public Path(std_msgs.msg.Header header, System.Collections.Generic.List<geometry_msgs.msg.PoseStamped>  poses)
				{
					this.header = header;
					this.poses = poses;
				}

				new public static string GetMessageType()
				{
					return "nav_msgs/msg/Path";
				}

			} // class Path
		} // namespace msg
	} // namespace nav_msgs
} // namespace SIGVerse.RosBridge
