// Generated by gencs from shape_msgs/msg/Mesh.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.shape_msgs.msg;
using SIGVerse.RosBridge.geometry_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace shape_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class Mesh : RosMessage
			{
				public System.Collections.Generic.List<shape_msgs.msg.MeshTriangle>  triangles;
				public System.Collections.Generic.List<UnityEngine.Vector3>  vertices;


				public Mesh()
				{
					this.triangles = new System.Collections.Generic.List<shape_msgs.msg.MeshTriangle>();
					this.vertices = new System.Collections.Generic.List<UnityEngine.Vector3>();
				}

				public Mesh(System.Collections.Generic.List<shape_msgs.msg.MeshTriangle>  triangles, System.Collections.Generic.List<UnityEngine.Vector3>  vertices)
				{
					this.triangles = triangles;
					this.vertices = vertices;
				}

				new public static string GetMessageType()
				{
					return "shape_msgs/msg/Mesh";
				}

			} // class Mesh
		} // namespace msg
	} // namespace shape_msgs
} // namespace SIGVerse.RosBridge
