// Generated by gencs from shape_msgs/msg/MeshTriangle.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace shape_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class MeshTriangle : RosMessage
			{
				public System.UInt32[]  vertex_indices;


				public MeshTriangle()
				{
					this.vertex_indices = new System.UInt32[3];
				}

				public MeshTriangle(System.UInt32[]  vertex_indices)
				{
					this.vertex_indices = vertex_indices;
				}

				new public static string GetMessageType()
				{
					return "shape_msgs/msg/MeshTriangle";
				}

			} // class MeshTriangle
		} // namespace msg
	} // namespace shape_msgs
} // namespace SIGVerse.RosBridge
