// Generated by gencs from shape_msgs/msg/Plane.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace shape_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class Plane : RosMessage
			{
				public double[]  coef;


				public Plane()
				{
					this.coef = new double[4];
				}

				public Plane(double[]  coef)
				{
					this.coef = coef;
				}

				new public static string GetMessageType()
				{
					return "shape_msgs/msg/Plane";
				}

			} // class Plane
		} // namespace msg
	} // namespace shape_msgs
} // namespace SIGVerse.RosBridge
