// Generated by gencs from shape_msgs/msg/SolidPrimitive.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.geometry_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace shape_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class SolidPrimitive : RosMessage
			{
				public byte type;
				public System.Collections.Generic.List<double>  dimensions;
				public geometry_msgs.msg.Polygon polygon;

				// Constants:
				public const byte BOX = 1;
				public const byte SPHERE = 2;
				public const byte CYLINDER = 3;
				public const byte CONE = 4;
				public const byte PRISM = 5;
				public const byte BOX_X = 0;
				public const byte BOX_Y = 1;
				public const byte BOX_Z = 2;
				public const byte SPHERE_RADIUS = 0;
				public const byte CYLINDER_HEIGHT = 0;
				public const byte CYLINDER_RADIUS = 1;
				public const byte CONE_HEIGHT = 0;
				public const byte CONE_RADIUS = 1;
				public const byte PRISM_HEIGHT = 0;

				public SolidPrimitive()
				{
					this.type = 0;
					this.dimensions = new System.Collections.Generic.List<double>();
					this.polygon = new geometry_msgs.msg.Polygon();
				}

				public SolidPrimitive(byte type, System.Collections.Generic.List<double>  dimensions, geometry_msgs.msg.Polygon polygon)
				{
					this.type = type;
					this.dimensions = dimensions;
					this.polygon = polygon;
				}

				new public static string GetMessageType()
				{
					return "shape_msgs/msg/SolidPrimitive";
				}

			} // class SolidPrimitive
		} // namespace msg
	} // namespace shape_msgs
} // namespace SIGVerse.RosBridge
