// Generated by gencs from sensor_msgs/CompressedImage.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs;

namespace SIGVerse.RosBridge 
{
	namespace sensor_msgs 
	{
		[System.Serializable]
		public class CompressedImage : RosMessage
		{
			public std_msgs.Header header;
			public string format;
			public System.Collections.Generic.List<byte>  data;


			public CompressedImage()
			{
				this.header = new std_msgs.Header();
				this.format = "";
				this.data = new System.Collections.Generic.List<byte>();
			}

			public CompressedImage(std_msgs.Header header, string format, System.Collections.Generic.List<byte>  data)
			{
				this.header = header;
				this.format = format;
				this.data = data;
			}

			new public static string GetMessageType()
			{
				return "sensor_msgs/CompressedImage";
			}

			new public static string GetMD5Hash()
			{
				return "8f7a12909da2c9d3332d540a0977563f";
			}
		} // class CompressedImage
	} // namespace sensor_msgs
} // namespace SIGVerse.ROSBridge

