// Generated by gencs from sensor_msgs/NavSatFix.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs;
using SIGVerse.RosBridge.sensor_msgs;

namespace SIGVerse.RosBridge 
{
	namespace sensor_msgs 
	{
		[System.Serializable]
		public class NavSatFix : RosMessage
		{
			public std_msgs.Header header;
			public sensor_msgs.NavSatStatus status;
			public double latitude;
			public double longitude;
			public double altitude;
			public double[]  position_covariance;
			public byte position_covariance_type;

			public const byte COVARIANCE_TYPE_UNKNOWN = 0;
			public const byte COVARIANCE_TYPE_APPROXIMATED = 1;
			public const byte COVARIANCE_TYPE_DIAGONAL_KNOWN = 2;
			public const byte COVARIANCE_TYPE_KNOWN = 3;

			public NavSatFix()
			{
				this.header = new std_msgs.Header();
				this.status = new sensor_msgs.NavSatStatus();
				this.latitude = 0.0;
				this.longitude = 0.0;
				this.altitude = 0.0;
				this.position_covariance = new double[9];
				this.position_covariance_type = 0;
			}

			public NavSatFix(std_msgs.Header header, sensor_msgs.NavSatStatus status, double latitude, double longitude, double altitude, double[]  position_covariance, byte position_covariance_type)
			{
				this.header = header;
				this.status = status;
				this.latitude = latitude;
				this.longitude = longitude;
				this.altitude = altitude;
				this.position_covariance = position_covariance;
				this.position_covariance_type = position_covariance_type;
			}

			new public static string GetMessageType()
			{
				return "sensor_msgs/NavSatFix";
			}

			new public static string GetMD5Hash()
			{
				return "2d3a8cd499b9b4a0249fb98fd05cfa48";
			}
		} // class NavSatFix
	} // namespace sensor_msgs
} // namespace SIGVerse.ROSBridge

