// Generated by gencs from sensor_msgs/Range.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs;

namespace SIGVerse.RosBridge 
{
	namespace sensor_msgs 
	{
		[System.Serializable]
		public class Range : RosMessage
		{
			public std_msgs.Header header;
			public byte radiation_type;
			public float field_of_view;
			public float min_range;
			public float max_range;
			public float range;

			public const byte ULTRASOUND = 0;
			public const byte INFRARED = 1;

			public Range()
			{
				this.header = new std_msgs.Header();
				this.radiation_type = 0;
				this.field_of_view = 0.0f;
				this.min_range = 0.0f;
				this.max_range = 0.0f;
				this.range = 0.0f;
			}

			public Range(std_msgs.Header header, byte radiation_type, float field_of_view, float min_range, float max_range, float range)
			{
				this.header = header;
				this.radiation_type = radiation_type;
				this.field_of_view = field_of_view;
				this.min_range = min_range;
				this.max_range = max_range;
				this.range = range;
			}

			new public static string GetMessageType()
			{
				return "sensor_msgs/Range";
			}

			new public static string GetMD5Hash()
			{
				return "c005c34273dc426c67a020a87bc24148";
			}
		} // class Range
	} // namespace sensor_msgs
} // namespace SIGVerse.ROSBridge

