// Generated by gencs from sensor_msgs/RegionOfInterest.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace sensor_msgs 
	{
		[System.Serializable]
		public class RegionOfInterest : RosMessage
		{
			public System.UInt32 x_offset;
			public System.UInt32 y_offset;
			public System.UInt32 height;
			public System.UInt32 width;
			public bool do_rectify;


			public RegionOfInterest()
			{
				this.x_offset = 0;
				this.y_offset = 0;
				this.height = 0;
				this.width = 0;
				this.do_rectify = false;
			}

			public RegionOfInterest(System.UInt32 x_offset, System.UInt32 y_offset, System.UInt32 height, System.UInt32 width, bool do_rectify)
			{
				this.x_offset = x_offset;
				this.y_offset = y_offset;
				this.height = height;
				this.width = width;
				this.do_rectify = do_rectify;
			}

			new public static string GetMessageType()
			{
				return "sensor_msgs/RegionOfInterest";
			}

			new public static string GetMD5Hash()
			{
				return "bdb633039d588fcccb441a4d43ccfe09";
			}
		} // class RegionOfInterest
	} // namespace sensor_msgs
} // namespace SIGVerse.ROSBridge

