// Generated by gencs from file sensor_msgs/SetCameraInfo.srv
// DO NOT EDIT THIS FILE BY HAND


using SIGVerse.RosBridge.sensor_msgs;

namespace SIGVerse.RosBridge 
{
	namespace sensor_msgs 
	{
		public class SetCameraInfo : RosBridgeServiceProvider<sensor_msgs.SetCameraInfoRequest>
		{
			public SetCameraInfo(string serviceName) : base(serviceName)
			{
				base.type = "sensor_msgs/SetCameraInfo";
			}

			public SetCameraInfo(string serviceName, string typeName = "sensor_msgs/SetCameraInfo") : base(serviceName, typeName) 
			{
			}
		}
	} // namespace sensor_msgs
} // namespace SIGVerse.ROSBridge

