// Generated by gencs from sensor_msgs/Temperature.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs;

namespace SIGVerse.RosBridge 
{
	namespace sensor_msgs 
	{
		[System.Serializable]
		public class Temperature : RosMessage
		{
			public std_msgs.Header header;
			public double temperature;
			public double variance;


			public Temperature()
			{
				this.header = new std_msgs.Header();
				this.temperature = 0.0;
				this.variance = 0.0;
			}

			public Temperature(std_msgs.Header header, double temperature, double variance)
			{
				this.header = header;
				this.temperature = temperature;
				this.variance = variance;
			}

			new public static string GetMessageType()
			{
				return "sensor_msgs/Temperature";
			}

			new public static string GetMD5Hash()
			{
				return "ff71b307acdbe7c871a5a6d7ed359100";
			}
		} // class Temperature
	} // namespace sensor_msgs
} // namespace SIGVerse.ROSBridge

