// Generated by gencs from file turtlesim/Kill.srv
// DO NOT EDIT THIS FILE BY HAND


using SIGVerse.RosBridge.turtlesim;

namespace SIGVerse.RosBridge 
{
	namespace turtlesim 
	{
		public class Kill : RosBridgeServiceProvider<turtlesim.KillRequest>
		{
			public Kill(string serviceName) : base(serviceName)
			{
				base.type = "turtlesim/Kill";
			}

			public Kill(string serviceName, string typeName = "turtlesim/Kill") : base(serviceName, typeName) 
			{
			}
		}
	} // namespace turtlesim
} // namespace SIGVerse.ROSBridge

