// Generated by gencs from turtlesim/SetPen.srv
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace turtlesim 
	{
		[System.Serializable]
		public class SetPenRequest : ServiceArgs
		{
			public byte r;
			public byte g;
			public byte b;
			public byte width;
			public byte off;


			public SetPenRequest()
			{
				this.r = 0;
				this.g = 0;
				this.b = 0;
				this.width = 0;
				this.off = 0;
			}

			public SetPenRequest(byte r, byte g, byte b, byte width, byte off)
			{
				this.r = r;
				this.g = g;
				this.b = b;
				this.width = width;
				this.off = off;
			}

			new public static string GetMessageType()
			{
				return "turtlesim/SetPenRequest";
			}

			new public static string GetMD5Hash()
			{
				return "9f452acce566bf0c0954594f69a8e41b";
			}
		} // class SetPenRequest
	} // namespace turtlesim
} // namespace SIGVerse.ROSBridge

