// Generated by gencs from std_srvs/srv/Empty.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace std_srvs 
	{
		namespace srv 
		{
			public class Empty : RosBridgeServiceProvider<Empty_Request>
			{

				public Empty(string serviceName) : base(serviceName)
				{
					base.type = "std_srvs/srv/Empty";
				}

				public Empty(string serviceName, string serviceType = "std_srvs/srv/Empty") : base(serviceName, serviceType) {}

			} // class Empty

			[System.Serializable]
			public class Empty_Request : ServiceArgs
			{
				public byte structure_needs_at_least_one_member;


				public Empty_Request()
				{
					this.structure_needs_at_least_one_member = 0;
				}

				public Empty_Request(byte structure_needs_at_least_one_member)
				{
					this.structure_needs_at_least_one_member = structure_needs_at_least_one_member;
				}

				new public static string GetMessageType()
				{
					return "std_srvs/srv/Empty_Request";
				}

			} // class Empty_Request

			[System.Serializable]
			public class Empty_Response : ServiceResponse
			{
				public byte structure_needs_at_least_one_member;


				public Empty_Response()
				{
					this.structure_needs_at_least_one_member = 0;
				}

				public Empty_Response(byte structure_needs_at_least_one_member)
				{
					this.structure_needs_at_least_one_member = structure_needs_at_least_one_member;
				}

				new public static string GetMessageType()
				{
					return "std_srvs/srv/Empty_Response";
				}

			} // class Empty_Response
		} // namespace srv
	} // namespace std_srvs
} // namespace SIGVerse.RosBridge
