// Generated by gencs from std_srvs/srv/SetBool.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace std_srvs 
	{
		namespace srv 
		{
			public class SetBool : RosBridgeServiceProvider<SetBool_Request>
			{

				public SetBool(string serviceName) : base(serviceName)
				{
					base.type = "std_srvs/srv/SetBool";
				}

				public SetBool(string serviceName, string serviceType = "std_srvs/srv/SetBool") : base(serviceName, serviceType) {}

			} // class SetBool

			[System.Serializable]
			public class SetBool_Request : ServiceArgs
			{
				public bool data;


				public SetBool_Request()
				{
					this.data = false;
				}

				public SetBool_Request(bool data)
				{
					this.data = data;
				}

				new public static string GetMessageType()
				{
					return "std_srvs/srv/SetBool_Request";
				}

			} // class SetBool_Request

			[System.Serializable]
			public class SetBool_Response : ServiceResponse
			{
				public bool success;
				public string message;


				public SetBool_Response()
				{
					this.success = false;
					this.message = "";
				}

				public SetBool_Response(bool success, string message)
				{
					this.success = success;
					this.message = message;
				}

				new public static string GetMessageType()
				{
					return "std_srvs/srv/SetBool_Response";
				}

			} // class SetBool_Response
		} // namespace srv
	} // namespace std_srvs
} // namespace SIGVerse.RosBridge
