// Generated by gencs from std_srvs/srv/Trigger.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace std_srvs 
	{
		namespace srv 
		{
			public class Trigger : RosBridgeServiceProvider<Trigger_Request>
			{

				public Trigger(string serviceName) : base(serviceName)
				{
					base.type = "std_srvs/srv/Trigger";
				}

				public Trigger(string serviceName, string serviceType = "std_srvs/srv/Trigger") : base(serviceName, serviceType) {}

			} // class Trigger

			[System.Serializable]
			public class Trigger_Request : ServiceArgs
			{
				public byte structure_needs_at_least_one_member;


				public Trigger_Request()
				{
					this.structure_needs_at_least_one_member = 0;
				}

				public Trigger_Request(byte structure_needs_at_least_one_member)
				{
					this.structure_needs_at_least_one_member = structure_needs_at_least_one_member;
				}

				new public static string GetMessageType()
				{
					return "std_srvs/srv/Trigger_Request";
				}

			} // class Trigger_Request

			[System.Serializable]
			public class Trigger_Response : ServiceResponse
			{
				public bool success;
				public string message;


				public Trigger_Response()
				{
					this.success = false;
					this.message = "";
				}

				public Trigger_Response(bool success, string message)
				{
					this.success = success;
					this.message = message;
				}

				new public static string GetMessageType()
				{
					return "std_srvs/srv/Trigger_Response";
				}

			} // class Trigger_Response
		} // namespace srv
	} // namespace std_srvs
} // namespace SIGVerse.RosBridge
