// Generated by gencs from std_msgs/ByteMultiArray.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs;

namespace SIGVerse.RosBridge 
{
	namespace std_msgs 
	{
		[System.Serializable]
		public class ByteMultiArray : RosMessage
		{
			public std_msgs.MultiArrayLayout layout;
			public System.Collections.Generic.List<sbyte>  data;


			public ByteMultiArray()
			{
				this.layout = new std_msgs.MultiArrayLayout();
				this.data = new System.Collections.Generic.List<sbyte>();
			}

			public ByteMultiArray(std_msgs.MultiArrayLayout layout, System.Collections.Generic.List<sbyte>  data)
			{
				this.layout = layout;
				this.data = data;
			}

			new public static string GetMessageType()
			{
				return "std_msgs/ByteMultiArray";
			}

			new public static string GetMD5Hash()
			{
				return "70ea476cbcfd65ac2f68f3cda1e891fe";
			}
		} // class ByteMultiArray
	} // namespace std_msgs
} // namespace SIGVerse.ROSBridge

