// Generated by gencs from std_msgs/Duration.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace std_msgs 
	{
		[System.Serializable]
		public class Duration : RosMessage
		{
			public SIGVerse.RosBridge.msg_helpers.Duration data;


			public Duration()
			{
				this.data = new SIGVerse.RosBridge.msg_helpers.Duration();
			}

			public Duration(SIGVerse.RosBridge.msg_helpers.Duration data)
			{
				this.data = data;
			}

			new public static string GetMessageType()
			{
				return "std_msgs/Duration";
			}

			new public static string GetMD5Hash()
			{
				return "3e286caf4241d664e55f3ad380e2ae46";
			}
		} // class Duration
	} // namespace std_msgs
} // namespace SIGVerse.ROSBridge

