// Generated by gencs from std_msgs/Float64.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace std_msgs 
	{
		[System.Serializable]
		public class Float64 : RosMessage
		{
			public double data;


			public Float64()
			{
				this.data = 0.0;
			}

			public Float64(double data)
			{
				this.data = data;
			}

			new public static string GetMessageType()
			{
				return "std_msgs/Float64";
			}

			new public static string GetMD5Hash()
			{
				return "fdb28210bfa9d7c91146260178d9a584";
			}
		} // class Float64
	} // namespace std_msgs
} // namespace SIGVerse.ROSBridge

