// Generated by gencs from std_msgs/Float64MultiArray.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs;

namespace SIGVerse.RosBridge 
{
	namespace std_msgs 
	{
		[System.Serializable]
		public class Float64MultiArray : RosMessage
		{
			public std_msgs.MultiArrayLayout layout;
			public System.Collections.Generic.List<double>  data;


			public Float64MultiArray()
			{
				this.layout = new std_msgs.MultiArrayLayout();
				this.data = new System.Collections.Generic.List<double>();
			}

			public Float64MultiArray(std_msgs.MultiArrayLayout layout, System.Collections.Generic.List<double>  data)
			{
				this.layout = layout;
				this.data = data;
			}

			new public static string GetMessageType()
			{
				return "std_msgs/Float64MultiArray";
			}

			new public static string GetMD5Hash()
			{
				return "4b7d974086d4060e7db4613a7e6c3ba4";
			}
		} // class Float64MultiArray
	} // namespace std_msgs
} // namespace SIGVerse.ROSBridge

