// Generated by gencs from std_msgs/Int64.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace std_msgs 
	{
		[System.Serializable]
		public class Int64 : RosMessage
		{
			public System.Int64 data;


			public Int64()
			{
				this.data = 0;
			}

			public Int64(System.Int64 data)
			{
				this.data = data;
			}

			new public static string GetMessageType()
			{
				return "std_msgs/Int64";
			}

			new public static string GetMD5Hash()
			{
				return "34add168574510e6e17f5d23ecc077ef";
			}
		} // class Int64
	} // namespace std_msgs
} // namespace SIGVerse.ROSBridge

