// Generated by gencs from std_msgs/MultiArrayLayout.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs;

namespace SIGVerse.RosBridge 
{
	namespace std_msgs 
	{
		[System.Serializable]
		public class MultiArrayLayout : RosMessage
		{
			public System.Collections.Generic.List<std_msgs.MultiArrayDimension>  dim;
			public System.UInt32 data_offset;


			public MultiArrayLayout()
			{
				this.dim = new System.Collections.Generic.List<std_msgs.MultiArrayDimension>();
				this.data_offset = 0;
			}

			public MultiArrayLayout(System.Collections.Generic.List<std_msgs.MultiArrayDimension>  dim, System.UInt32 data_offset)
			{
				this.dim = dim;
				this.data_offset = data_offset;
			}

			new public static string GetMessageType()
			{
				return "std_msgs/MultiArrayLayout";
			}

			new public static string GetMD5Hash()
			{
				return "0fed2a11c13e11c5571b4e2a995a91a3";
			}
		} // class MultiArrayLayout
	} // namespace std_msgs
} // namespace SIGVerse.ROSBridge

