// Generated by gencs from diagnostic_msgs/srv/AddDiagnostics.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace diagnostic_msgs 
	{
		namespace srv 
		{
			public class AddDiagnostics : RosBridgeServiceProvider<AddDiagnostics_Request>
			{

				public AddDiagnostics(string serviceName) : base(serviceName)
				{
					base.type = "diagnostic_msgs/srv/AddDiagnostics";
				}

				public AddDiagnostics(string serviceName, string serviceType = "diagnostic_msgs/srv/AddDiagnostics") : base(serviceName, serviceType) {}

			} // class AddDiagnostics

			[System.Serializable]
			public class AddDiagnostics_Request : ServiceArgs
			{
				public string load_namespace;


				public AddDiagnostics_Request()
				{
					this.load_namespace = "";
				}

				public AddDiagnostics_Request(string load_namespace)
				{
					this.load_namespace = load_namespace;
				}

				new public static string GetMessageType()
				{
					return "diagnostic_msgs/srv/AddDiagnostics_Request";
				}

			} // class AddDiagnostics_Request

			[System.Serializable]
			public class AddDiagnostics_Response : ServiceResponse
			{
				public bool success;
				public string message;


				public AddDiagnostics_Response()
				{
					this.success = false;
					this.message = "";
				}

				public AddDiagnostics_Response(bool success, string message)
				{
					this.success = success;
					this.message = message;
				}

				new public static string GetMessageType()
				{
					return "diagnostic_msgs/srv/AddDiagnostics_Response";
				}

			} // class AddDiagnostics_Response
		} // namespace srv
	} // namespace diagnostic_msgs
} // namespace SIGVerse.RosBridge
