// Generated by gencs from diagnostic_msgs/srv/SelfTest.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace diagnostic_msgs 
	{
		namespace srv 
		{
			public class SelfTest : RosBridgeServiceProvider<SelfTest_Request>
			{

				public SelfTest(string serviceName) : base(serviceName)
				{
					base.type = "diagnostic_msgs/srv/SelfTest";
				}

				public SelfTest(string serviceName, string serviceType = "diagnostic_msgs/srv/SelfTest") : base(serviceName, serviceType) {}

			} // class SelfTest

			[System.Serializable]
			public class SelfTest_Request : ServiceArgs
			{
				public byte structure_needs_at_least_one_member;


				public SelfTest_Request()
				{
					this.structure_needs_at_least_one_member = 0;
				}

				public SelfTest_Request(byte structure_needs_at_least_one_member)
				{
					this.structure_needs_at_least_one_member = structure_needs_at_least_one_member;
				}

				new public static string GetMessageType()
				{
					return "diagnostic_msgs/srv/SelfTest_Request";
				}

			} // class SelfTest_Request

			[System.Serializable]
			public class SelfTest_Response : ServiceResponse
			{
				public string id;
				public sbyte passed;
				public System.Collections.Generic.List<diagnostic_msgs.msg.DiagnosticStatus>  status;


				public SelfTest_Response()
				{
					this.id = "";
					this.passed = 0;
					this.status = new System.Collections.Generic.List<diagnostic_msgs.msg.DiagnosticStatus>();
				}

				public SelfTest_Response(string id, sbyte passed, System.Collections.Generic.List<diagnostic_msgs.msg.DiagnosticStatus>  status)
				{
					this.id = id;
					this.passed = passed;
					this.status = status;
				}

				new public static string GetMessageType()
				{
					return "diagnostic_msgs/srv/SelfTest_Response";
				}

			} // class SelfTest_Response
		} // namespace srv
	} // namespace diagnostic_msgs
} // namespace SIGVerse.RosBridge
