// Generated by gencs from pr2_controllers_msgs/Pr2GripperCommand.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace pr2_controllers_msgs 
	{
		[System.Serializable]
		public class Pr2GripperCommand : RosMessage
		{
			public double position;
			public double max_effort;


			public Pr2GripperCommand()
			{
				this.position = 0.0;
				this.max_effort = 0.0;
			}

			public Pr2GripperCommand(double position, double max_effort)
			{
				this.position = position;
				this.max_effort = max_effort;
			}

			new public static string GetMessageType()
			{
				return "pr2_controllers_msgs/Pr2GripperCommand";
			}

			new public static string GetMD5Hash()
			{
				return "680acaff79486f017132a7f198d40f08";
			}
		} // class Pr2GripperCommand
	} // namespace pr2_controllers_msgs
} // namespace SIGVerse.RosBridge

