// Generated by gencs from visualization_msgs/InteractiveMarkerPose.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs;
using SIGVerse.RosBridge.geometry_msgs;

namespace SIGVerse.RosBridge 
{
	namespace visualization_msgs 
	{
		[System.Serializable]
		public class InteractiveMarkerPose : RosMessage
		{
			public std_msgs.Header header;
			public geometry_msgs.Pose pose;
			public string name;


			public InteractiveMarkerPose()
			{
				this.header = new std_msgs.Header();
				this.pose = new geometry_msgs.Pose();
				this.name = "";
			}

			public InteractiveMarkerPose(std_msgs.Header header, geometry_msgs.Pose pose, string name)
			{
				this.header = header;
				this.pose = pose;
				this.name = name;
			}

			new public static string GetMessageType()
			{
				return "visualization_msgs/InteractiveMarkerPose";
			}

			new public static string GetMD5Hash()
			{
				return "a6e6833209a196a38d798dadb02c81f8";
			}
		} // class InteractiveMarkerPose
	} // namespace visualization_msgs
} // namespace SIGVerse.ROSBridge

