// Generated by gencs from visualization_msgs/InteractiveMarkerUpdate.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.visualization_msgs;

namespace SIGVerse.RosBridge 
{
	namespace visualization_msgs 
	{
		[System.Serializable]
		public class InteractiveMarkerUpdate : RosMessage
		{
			public string server_id;
			public System.UInt64 seq_num;
			public byte type;
			public System.Collections.Generic.List<visualization_msgs.InteractiveMarker>  markers;
			public System.Collections.Generic.List<visualization_msgs.InteractiveMarkerPose>  poses;
			public System.Collections.Generic.List<string>  erases;

			public const byte KEEP_ALIVE = 0;
			public const byte UPDATE = 1;

			public InteractiveMarkerUpdate()
			{
				this.server_id = "";
				this.seq_num = 0;
				this.type = 0;
				this.markers = new System.Collections.Generic.List<visualization_msgs.InteractiveMarker>();
				this.poses = new System.Collections.Generic.List<visualization_msgs.InteractiveMarkerPose>();
				this.erases = new System.Collections.Generic.List<string>();
			}

			public InteractiveMarkerUpdate(string server_id, System.UInt64 seq_num, byte type, System.Collections.Generic.List<visualization_msgs.InteractiveMarker>  markers, System.Collections.Generic.List<visualization_msgs.InteractiveMarkerPose>  poses, System.Collections.Generic.List<string>  erases)
			{
				this.server_id = server_id;
				this.seq_num = seq_num;
				this.type = type;
				this.markers = markers;
				this.poses = poses;
				this.erases = erases;
			}

			new public static string GetMessageType()
			{
				return "visualization_msgs/InteractiveMarkerUpdate";
			}

			new public static string GetMD5Hash()
			{
				return "710d308d0a9276d65945e92dd30b3946";
			}
		} // class InteractiveMarkerUpdate
	} // namespace visualization_msgs
} // namespace SIGVerse.ROSBridge

