// Generated by gencs from stereo_msgs/msg/DisparityImage.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs.msg;
using SIGVerse.RosBridge.sensor_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace stereo_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class DisparityImage : RosMessage
			{
				public std_msgs.msg.Header header;
				public sensor_msgs.msg.Image image;
				public float f;
				public float t;
				public sensor_msgs.msg.RegionOfInterest valid_window;
				public float min_disparity;
				public float max_disparity;
				public float delta_d;


				public DisparityImage()
				{
					this.header = new std_msgs.msg.Header();
					this.image = new sensor_msgs.msg.Image();
					this.f = 0.0f;
					this.t = 0.0f;
					this.valid_window = new sensor_msgs.msg.RegionOfInterest();
					this.min_disparity = 0.0f;
					this.max_disparity = 0.0f;
					this.delta_d = 0.0f;
				}

				public DisparityImage(std_msgs.msg.Header header, sensor_msgs.msg.Image image, float f, float t, sensor_msgs.msg.RegionOfInterest valid_window, float min_disparity, float max_disparity, float delta_d)
				{
					this.header = header;
					this.image = image;
					this.f = f;
					this.t = t;
					this.valid_window = valid_window;
					this.min_disparity = min_disparity;
					this.max_disparity = max_disparity;
					this.delta_d = delta_d;
				}

				new public static string GetMessageType()
				{
					return "stereo_msgs/msg/DisparityImage";
				}

			} // class DisparityImage
		} // namespace msg
	} // namespace stereo_msgs
} // namespace SIGVerse.RosBridge
