// Generated by gencs from actionlib_msgs/GoalStatusArray.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs;
using SIGVerse.RosBridge.actionlib_msgs;

namespace SIGVerse.RosBridge 
{
	namespace actionlib_msgs 
	{
		[System.Serializable]
		public class GoalStatusArray : RosMessage
		{
			public std_msgs.Header header;
			public System.Collections.Generic.List<actionlib_msgs.GoalStatus>  status_list;


			public GoalStatusArray()
			{
				this.header = new std_msgs.Header();
				this.status_list = new System.Collections.Generic.List<actionlib_msgs.GoalStatus>();
			}

			public GoalStatusArray(std_msgs.Header header, System.Collections.Generic.List<actionlib_msgs.GoalStatus>  status_list)
			{
				this.header = header;
				this.status_list = status_list;
			}

			new public static string GetMessageType()
			{
				return "actionlib_msgs/GoalStatusArray";
			}

			new public static string GetMD5Hash()
			{
				return "8b2b82f13216d0a8ea88bd3af735e619";
			}
		} // class GoalStatusArray
	} // namespace actionlib_msgs
} // namespace SIGVerse.ROSBridge

