// Generated by gencs from actionlib_msgs/GoalID.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace actionlib_msgs 
	{
		[System.Serializable]
		public class GoalID : RosMessage
		{
			public SIGVerse.RosBridge.msg_helpers.Time stamp;
			public string id;


			public GoalID()
			{
				this.stamp = new SIGVerse.RosBridge.msg_helpers.Time();
				this.id = "";
			}

			public GoalID(SIGVerse.RosBridge.msg_helpers.Time stamp, string id)
			{
				this.stamp = stamp;
				this.id = id;
			}

			new public static string GetMessageType()
			{
				return "actionlib_msgs/GoalID";
			}

			new public static string GetMD5Hash()
			{
				return "302881f31927c1df708a2dbab0e80ee8";
			}
		} // class GoalID
	} // namespace actionlib_msgs
} // namespace SIGVerse.ROSBridge

