// Generated by gencs from std_msgs/Int16.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace std_msgs 
	{
		[System.Serializable]
		public class Int16 : RosMessage
		{
			public System.Int16 data;


			public Int16()
			{
				this.data = 0;
			}

			public Int16(System.Int16 data)
			{
				this.data = data;
			}

			new public static string GetMessageType()
			{
				return "std_msgs/Int16";
			}

			new public static string GetMD5Hash()
			{
				return "8524586e34fbd7cb1c08c5f5f1ca0e57";
			}
		} // class Int16
	} // namespace std_msgs
} // namespace SIGVerse.ROSBridge

