// Generated by gencs from std_msgs/UInt32MultiArray.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs;

namespace SIGVerse.RosBridge 
{
	namespace std_msgs 
	{
		[System.Serializable]
		public class UInt32MultiArray : RosMessage
		{
			public std_msgs.MultiArrayLayout layout;
			public System.Collections.Generic.List<System.UInt32>  data;


			public UInt32MultiArray()
			{
				this.layout = new std_msgs.MultiArrayLayout();
				this.data = new System.Collections.Generic.List<System.UInt32>();
			}

			public UInt32MultiArray(std_msgs.MultiArrayLayout layout, System.Collections.Generic.List<System.UInt32>  data)
			{
				this.layout = layout;
				this.data = data;
			}

			new public static string GetMessageType()
			{
				return "std_msgs/UInt32MultiArray";
			}

			new public static string GetMD5Hash()
			{
				return "4d6a180abc9be191b96a7eda6c8a233d";
			}
		} // class UInt32MultiArray
	} // namespace std_msgs
} // namespace SIGVerse.ROSBridge

