// Generated by gencs from std_msgs/UInt8.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace std_msgs 
	{
		[System.Serializable]
		public class UInt8 : RosMessage
		{
			public byte data;


			public UInt8()
			{
				this.data = 0;
			}

			public UInt8(byte data)
			{
				this.data = data;
			}

			new public static string GetMessageType()
			{
				return "std_msgs/UInt8";
			}

			new public static string GetMD5Hash()
			{
				return "7c8164229e7d2c17eb95e9231617fdee";
			}
		} // class UInt8
	} // namespace std_msgs
} // namespace SIGVerse.ROSBridge

