// Generated by gencs from visualization_msgs/msg/ImageMarker.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs.msg;
using SIGVerse.RosBridge.geometry_msgs.msg;
using SIGVerse.RosBridge.builtin_interfaces.msg;

namespace SIGVerse.RosBridge 
{
	namespace visualization_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class ImageMarker : RosMessage
			{
				public std_msgs.msg.Header header;
				public string ns;
				public System.Int32 id;
				public System.Int32 type;
				public System.Int32 action;
				public UnityEngine.Vector3 position;
				public float scale;
				public std_msgs.msg.ColorRGBA outline_color;
				public byte filled;
				public std_msgs.msg.ColorRGBA fill_color;
				public builtin_interfaces.msg.Duration lifetime;
				public System.Collections.Generic.List<UnityEngine.Vector3>  points;
				public System.Collections.Generic.List<std_msgs.msg.ColorRGBA>  outline_colors;

				// Constants:
				public const System.Int32 CIRCLE = 0;
				public const System.Int32 LINE_STRIP = 1;
				public const System.Int32 LINE_LIST = 2;
				public const System.Int32 POLYGON = 3;
				public const System.Int32 POINTS = 4;
				public const System.Int32 ADD = 0;
				public const System.Int32 REMOVE = 1;

				public ImageMarker()
				{
					this.header = new std_msgs.msg.Header();
					this.ns = "";
					this.id = 0;
					this.type = 0;
					this.action = 0;
					this.position = new UnityEngine.Vector3();
					this.scale = 0.0f;
					this.outline_color = new std_msgs.msg.ColorRGBA();
					this.filled = 0;
					this.fill_color = new std_msgs.msg.ColorRGBA();
					this.lifetime = new builtin_interfaces.msg.Duration();
					this.points = new System.Collections.Generic.List<UnityEngine.Vector3>();
					this.outline_colors = new System.Collections.Generic.List<std_msgs.msg.ColorRGBA>();
				}

				public ImageMarker(std_msgs.msg.Header header, string ns, System.Int32 id, System.Int32 type, System.Int32 action, UnityEngine.Vector3 position, float scale, std_msgs.msg.ColorRGBA outline_color, byte filled, std_msgs.msg.ColorRGBA fill_color, builtin_interfaces.msg.Duration lifetime, System.Collections.Generic.List<UnityEngine.Vector3>  points, System.Collections.Generic.List<std_msgs.msg.ColorRGBA>  outline_colors)
				{
					this.header = header;
					this.ns = ns;
					this.id = id;
					this.type = type;
					this.action = action;
					this.position = position;
					this.scale = scale;
					this.outline_color = outline_color;
					this.filled = filled;
					this.fill_color = fill_color;
					this.lifetime = lifetime;
					this.points = points;
					this.outline_colors = outline_colors;
				}

				new public static string GetMessageType()
				{
					return "visualization_msgs/msg/ImageMarker";
				}

			} // class ImageMarker
		} // namespace msg
	} // namespace visualization_msgs
} // namespace SIGVerse.RosBridge
