// Generated by gencs from visualization_msgs/msg/InteractiveMarker.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs.msg;
using SIGVerse.RosBridge.geometry_msgs.msg;
using SIGVerse.RosBridge.visualization_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace visualization_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class InteractiveMarker : RosMessage
			{
				public std_msgs.msg.Header header;
				public geometry_msgs.msg.Pose pose;
				public string name;
				public string description;
				public float scale;
				public System.Collections.Generic.List<visualization_msgs.msg.MenuEntry>  menu_entries;
				public System.Collections.Generic.List<visualization_msgs.msg.InteractiveMarkerControl>  controls;


				public InteractiveMarker()
				{
					this.header = new std_msgs.msg.Header();
					this.pose = new geometry_msgs.msg.Pose();
					this.name = "";
					this.description = "";
					this.scale = 0.0f;
					this.menu_entries = new System.Collections.Generic.List<visualization_msgs.msg.MenuEntry>();
					this.controls = new System.Collections.Generic.List<visualization_msgs.msg.InteractiveMarkerControl>();
				}

				public InteractiveMarker(std_msgs.msg.Header header, geometry_msgs.msg.Pose pose, string name, string description, float scale, System.Collections.Generic.List<visualization_msgs.msg.MenuEntry>  menu_entries, System.Collections.Generic.List<visualization_msgs.msg.InteractiveMarkerControl>  controls)
				{
					this.header = header;
					this.pose = pose;
					this.name = name;
					this.description = description;
					this.scale = scale;
					this.menu_entries = menu_entries;
					this.controls = controls;
				}

				new public static string GetMessageType()
				{
					return "visualization_msgs/msg/InteractiveMarker";
				}

			} // class InteractiveMarker
		} // namespace msg
	} // namespace visualization_msgs
} // namespace SIGVerse.RosBridge
