// Generated by gencs from visualization_msgs/msg/InteractiveMarkerPose.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs.msg;
using SIGVerse.RosBridge.geometry_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace visualization_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class InteractiveMarkerPose : RosMessage
			{
				public std_msgs.msg.Header header;
				public geometry_msgs.msg.Pose pose;
				public string name;


				public InteractiveMarkerPose()
				{
					this.header = new std_msgs.msg.Header();
					this.pose = new geometry_msgs.msg.Pose();
					this.name = "";
				}

				public InteractiveMarkerPose(std_msgs.msg.Header header, geometry_msgs.msg.Pose pose, string name)
				{
					this.header = header;
					this.pose = pose;
					this.name = name;
				}

				new public static string GetMessageType()
				{
					return "visualization_msgs/msg/InteractiveMarkerPose";
				}

			} // class InteractiveMarkerPose
		} // namespace msg
	} // namespace visualization_msgs
} // namespace SIGVerse.RosBridge
