// Generated by gencs from visualization_msgs/msg/Marker.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs.msg;
using SIGVerse.RosBridge.geometry_msgs.msg;
using SIGVerse.RosBridge.builtin_interfaces.msg;
using SIGVerse.RosBridge.sensor_msgs.msg;
using SIGVerse.RosBridge.visualization_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace visualization_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class Marker : RosMessage
			{
				public std_msgs.msg.Header header;
				public string ns;
				public System.Int32 id;
				public System.Int32 type;
				public System.Int32 action;
				public geometry_msgs.msg.Pose pose;
				public UnityEngine.Vector3 scale;
				public std_msgs.msg.ColorRGBA color;
				public builtin_interfaces.msg.Duration lifetime;
				public bool frame_locked;
				public System.Collections.Generic.List<UnityEngine.Vector3>  points;
				public System.Collections.Generic.List<std_msgs.msg.ColorRGBA>  colors;
				public string texture_resource;
				public sensor_msgs.msg.CompressedImage texture;
				public System.Collections.Generic.List<visualization_msgs.msg.UVCoordinate>  uv_coordinates;
				public string text;
				public string mesh_resource;
				public visualization_msgs.msg.MeshFile mesh_file;
				public bool mesh_use_embedded_materials;

				// Constants:
				public const System.Int32 ARROW = 0;
				public const System.Int32 CUBE = 1;
				public const System.Int32 SPHERE = 2;
				public const System.Int32 CYLINDER = 3;
				public const System.Int32 LINE_STRIP = 4;
				public const System.Int32 LINE_LIST = 5;
				public const System.Int32 CUBE_LIST = 6;
				public const System.Int32 SPHERE_LIST = 7;
				public const System.Int32 POINTS = 8;
				public const System.Int32 TEXT_VIEW_FACING = 9;
				public const System.Int32 MESH_RESOURCE = 10;
				public const System.Int32 TRIANGLE_LIST = 11;
				public const System.Int32 ADD = 0;
				public const System.Int32 MODIFY = 0;
				public const System.Int32 DELETE = 2;
				public const System.Int32 DELETEALL = 3;

				public Marker()
				{
					this.header = new std_msgs.msg.Header();
					this.ns = "";
					this.id = 0;
					this.type = 0;
					this.action = 0;
					this.pose = new geometry_msgs.msg.Pose();
					this.scale = new UnityEngine.Vector3();
					this.color = new std_msgs.msg.ColorRGBA();
					this.lifetime = new builtin_interfaces.msg.Duration();
					this.frame_locked = false;
					this.points = new System.Collections.Generic.List<UnityEngine.Vector3>();
					this.colors = new System.Collections.Generic.List<std_msgs.msg.ColorRGBA>();
					this.texture_resource = "";
					this.texture = new sensor_msgs.msg.CompressedImage();
					this.uv_coordinates = new System.Collections.Generic.List<visualization_msgs.msg.UVCoordinate>();
					this.text = "";
					this.mesh_resource = "";
					this.mesh_file = new visualization_msgs.msg.MeshFile();
					this.mesh_use_embedded_materials = false;
				}

				public Marker(std_msgs.msg.Header header, string ns, System.Int32 id, System.Int32 type, System.Int32 action, geometry_msgs.msg.Pose pose, UnityEngine.Vector3 scale, std_msgs.msg.ColorRGBA color, builtin_interfaces.msg.Duration lifetime, bool frame_locked, System.Collections.Generic.List<UnityEngine.Vector3>  points, System.Collections.Generic.List<std_msgs.msg.ColorRGBA>  colors, string texture_resource, sensor_msgs.msg.CompressedImage texture, System.Collections.Generic.List<visualization_msgs.msg.UVCoordinate>  uv_coordinates, string text, string mesh_resource, visualization_msgs.msg.MeshFile mesh_file, bool mesh_use_embedded_materials)
				{
					this.header = header;
					this.ns = ns;
					this.id = id;
					this.type = type;
					this.action = action;
					this.pose = pose;
					this.scale = scale;
					this.color = color;
					this.lifetime = lifetime;
					this.frame_locked = frame_locked;
					this.points = points;
					this.colors = colors;
					this.texture_resource = texture_resource;
					this.texture = texture;
					this.uv_coordinates = uv_coordinates;
					this.text = text;
					this.mesh_resource = mesh_resource;
					this.mesh_file = mesh_file;
					this.mesh_use_embedded_materials = mesh_use_embedded_materials;
				}

				new public static string GetMessageType()
				{
					return "visualization_msgs/msg/Marker";
				}

			} // class Marker
		} // namespace msg
	} // namespace visualization_msgs
} // namespace SIGVerse.RosBridge
