// Generated by gencs from visualization_msgs/msg/MarkerArray.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.visualization_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace visualization_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class MarkerArray : RosMessage
			{
				public System.Collections.Generic.List<visualization_msgs.msg.Marker>  markers;


				public MarkerArray()
				{
					this.markers = new System.Collections.Generic.List<visualization_msgs.msg.Marker>();
				}

				public MarkerArray(System.Collections.Generic.List<visualization_msgs.msg.Marker>  markers)
				{
					this.markers = markers;
				}

				new public static string GetMessageType()
				{
					return "visualization_msgs/msg/MarkerArray";
				}

			} // class MarkerArray
		} // namespace msg
	} // namespace visualization_msgs
} // namespace SIGVerse.RosBridge
