// Generated by gencs from visualization_msgs/msg/MenuEntry.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace visualization_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class MenuEntry : RosMessage
			{
				public System.UInt32 id;
				public System.UInt32 parent_id;
				public string title;
				public string command;
				public byte command_type;

				// Constants:
				public const byte FEEDBACK = 0;
				public const byte ROSRUN = 1;
				public const byte ROSLAUNCH = 2;

				public MenuEntry()
				{
					this.id = 0;
					this.parent_id = 0;
					this.title = "";
					this.command = "";
					this.command_type = 0;
				}

				public MenuEntry(System.UInt32 id, System.UInt32 parent_id, string title, string command, byte command_type)
				{
					this.id = id;
					this.parent_id = parent_id;
					this.title = title;
					this.command = command;
					this.command_type = command_type;
				}

				new public static string GetMessageType()
				{
					return "visualization_msgs/msg/MenuEntry";
				}

			} // class MenuEntry
		} // namespace msg
	} // namespace visualization_msgs
} // namespace SIGVerse.RosBridge
