// Generated by gencs from visualization_msgs/msg/MeshFile.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace visualization_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class MeshFile : RosMessage
			{
				public string filename;
				public System.Collections.Generic.List<byte>  data;


				public MeshFile()
				{
					this.filename = "";
					this.data = new System.Collections.Generic.List<byte>();
				}

				public MeshFile(string filename, System.Collections.Generic.List<byte>  data)
				{
					this.filename = filename;
					this.data = data;
				}

				new public static string GetMessageType()
				{
					return "visualization_msgs/msg/MeshFile";
				}

			} // class MeshFile
		} // namespace msg
	} // namespace visualization_msgs
} // namespace SIGVerse.RosBridge
