// Generated by gencs from visualization_msgs/msg/UVCoordinate.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace visualization_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class UVCoordinate : RosMessage
			{
				public float u;
				public float v;


				public UVCoordinate()
				{
					this.u = 0.0f;
					this.v = 0.0f;
				}

				public UVCoordinate(float u, float v)
				{
					this.u = u;
					this.v = v;
				}

				new public static string GetMessageType()
				{
					return "visualization_msgs/msg/UVCoordinate";
				}

			} // class UVCoordinate
		} // namespace msg
	} // namespace visualization_msgs
} // namespace SIGVerse.RosBridge
