// Generated by gencs from nav_msgs/srv/GetMap.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace nav_msgs 
	{
		namespace srv 
		{
			public class GetMap : RosBridgeServiceProvider<GetMap_Request>
			{

				public GetMap(string serviceName) : base(serviceName)
				{
					base.type = "nav_msgs/srv/GetMap";
				}

				public GetMap(string serviceName, string serviceType = "nav_msgs/srv/GetMap") : base(serviceName, serviceType) {}

			} // class GetMap

			[System.Serializable]
			public class GetMap_Request : ServiceArgs
			{
				public byte structure_needs_at_least_one_member;


				public GetMap_Request()
				{
					this.structure_needs_at_least_one_member = 0;
				}

				public GetMap_Request(byte structure_needs_at_least_one_member)
				{
					this.structure_needs_at_least_one_member = structure_needs_at_least_one_member;
				}

				new public static string GetMessageType()
				{
					return "nav_msgs/srv/GetMap_Request";
				}

			} // class GetMap_Request

			[System.Serializable]
			public class GetMap_Response : ServiceResponse
			{
				public nav_msgs.msg.OccupancyGrid map;


				public GetMap_Response()
				{
					this.map = new nav_msgs.msg.OccupancyGrid();
				}

				public GetMap_Response(nav_msgs.msg.OccupancyGrid map)
				{
					this.map = map;
				}

				new public static string GetMessageType()
				{
					return "nav_msgs/srv/GetMap_Response";
				}

			} // class GetMap_Response
		} // namespace srv
	} // namespace nav_msgs
} // namespace SIGVerse.RosBridge
