// Generated by gencs from nav_msgs/srv/GetPlan.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace nav_msgs 
	{
		namespace srv 
		{
			public class GetPlan : RosBridgeServiceProvider<GetPlan_Request>
			{

				public GetPlan(string serviceName) : base(serviceName)
				{
					base.type = "nav_msgs/srv/GetPlan";
				}

				public GetPlan(string serviceName, string serviceType = "nav_msgs/srv/GetPlan") : base(serviceName, serviceType) {}

			} // class GetPlan

			[System.Serializable]
			public class GetPlan_Request : ServiceArgs
			{
				public geometry_msgs.msg.PoseStamped start;
				public geometry_msgs.msg.PoseStamped goal;
				public float tolerance;


				public GetPlan_Request()
				{
					this.start = new geometry_msgs.msg.PoseStamped();
					this.goal = new geometry_msgs.msg.PoseStamped();
					this.tolerance = 0.0f;
				}

				public GetPlan_Request(geometry_msgs.msg.PoseStamped start, geometry_msgs.msg.PoseStamped goal, float tolerance)
				{
					this.start = start;
					this.goal = goal;
					this.tolerance = tolerance;
				}

				new public static string GetMessageType()
				{
					return "nav_msgs/srv/GetPlan_Request";
				}

			} // class GetPlan_Request

			[System.Serializable]
			public class GetPlan_Response : ServiceResponse
			{
				public nav_msgs.msg.Path plan;


				public GetPlan_Response()
				{
					this.plan = new nav_msgs.msg.Path();
				}

				public GetPlan_Response(nav_msgs.msg.Path plan)
				{
					this.plan = plan;
				}

				new public static string GetMessageType()
				{
					return "nav_msgs/srv/GetPlan_Response";
				}

			} // class GetPlan_Response
		} // namespace srv
	} // namespace nav_msgs
} // namespace SIGVerse.RosBridge
