// Generated by gencs from nav_msgs/srv/LoadMap.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace nav_msgs 
	{
		namespace srv 
		{
			public class LoadMap : RosBridgeServiceProvider<LoadMap_Request>
			{

				public LoadMap(string serviceName) : base(serviceName)
				{
					base.type = "nav_msgs/srv/LoadMap";
				}

				public LoadMap(string serviceName, string serviceType = "nav_msgs/srv/LoadMap") : base(serviceName, serviceType) {}

			} // class LoadMap

			[System.Serializable]
			public class LoadMap_Request : ServiceArgs
			{
				public string map_url;


				public LoadMap_Request()
				{
					this.map_url = "";
				}

				public LoadMap_Request(string map_url)
				{
					this.map_url = map_url;
				}

				new public static string GetMessageType()
				{
					return "nav_msgs/srv/LoadMap_Request";
				}

			} // class LoadMap_Request

			[System.Serializable]
			public class LoadMap_Response : ServiceResponse
			{
				public nav_msgs.msg.OccupancyGrid map;
				public byte result;

				// Constants:
				public const byte RESULT_SUCCESS = 0;
				public const byte RESULT_MAP_DOES_NOT_EXIST = 1;
				public const byte RESULT_INVALID_MAP_DATA = 2;
				public const byte RESULT_INVALID_MAP_METADATA = 3;
				public const byte RESULT_UNDEFINED_FAILURE = 255;

				public LoadMap_Response()
				{
					this.map = new nav_msgs.msg.OccupancyGrid();
					this.result = 0;
				}

				public LoadMap_Response(nav_msgs.msg.OccupancyGrid map, byte result)
				{
					this.map = map;
					this.result = result;
				}

				new public static string GetMessageType()
				{
					return "nav_msgs/srv/LoadMap_Response";
				}

			} // class LoadMap_Response
		} // namespace srv
	} // namespace nav_msgs
} // namespace SIGVerse.RosBridge
