// Generated by gencs from nav_msgs/srv/SetMap.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace nav_msgs 
	{
		namespace srv 
		{
			public class SetMap : RosBridgeServiceProvider<SetMap_Request>
			{

				public SetMap(string serviceName) : base(serviceName)
				{
					base.type = "nav_msgs/srv/SetMap";
				}

				public SetMap(string serviceName, string serviceType = "nav_msgs/srv/SetMap") : base(serviceName, serviceType) {}

			} // class SetMap

			[System.Serializable]
			public class SetMap_Request : ServiceArgs
			{
				public nav_msgs.msg.OccupancyGrid map;
				public geometry_msgs.msg.PoseWithCovarianceStamped initial_pose;


				public SetMap_Request()
				{
					this.map = new nav_msgs.msg.OccupancyGrid();
					this.initial_pose = new geometry_msgs.msg.PoseWithCovarianceStamped();
				}

				public SetMap_Request(nav_msgs.msg.OccupancyGrid map, geometry_msgs.msg.PoseWithCovarianceStamped initial_pose)
				{
					this.map = map;
					this.initial_pose = initial_pose;
				}

				new public static string GetMessageType()
				{
					return "nav_msgs/srv/SetMap_Request";
				}

			} // class SetMap_Request

			[System.Serializable]
			public class SetMap_Response : ServiceResponse
			{
				public bool success;


				public SetMap_Response()
				{
					this.success = false;
				}

				public SetMap_Response(bool success)
				{
					this.success = success;
				}

				new public static string GetMessageType()
				{
					return "nav_msgs/srv/SetMap_Response";
				}

			} // class SetMap_Response
		} // namespace srv
	} // namespace nav_msgs
} // namespace SIGVerse.RosBridge
