// Generated by gencs from visualization_msgs/ImageMarker.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs;
using SIGVerse.RosBridge.geometry_msgs;

namespace SIGVerse.RosBridge 
{
	namespace visualization_msgs 
	{
		[System.Serializable]
		public class ImageMarker : RosMessage
		{
			public std_msgs.Header header;
			public string ns;
			public System.Int32 id;
			public System.Int32 type;
			public System.Int32 action;
			public UnityEngine.Vector3 position;
			public float scale;
			public std_msgs.ColorRGBA outline_color;
			public byte filled;
			public std_msgs.ColorRGBA fill_color;
			public SIGVerse.RosBridge.msg_helpers.Duration lifetime;
			public System.Collections.Generic.List<UnityEngine.Vector3>  points;
			public System.Collections.Generic.List<std_msgs.ColorRGBA>  outline_colors;

			public const byte CIRCLE = 0;
			public const byte LINE_STRIP = 1;
			public const byte LINE_LIST = 2;
			public const byte POLYGON = 3;
			public const byte POINTS = 4;
			public const byte ADD = 0;
			public const byte REMOVE = 1;

			public ImageMarker()
			{
				this.header = new std_msgs.Header();
				this.ns = "";
				this.id = 0;
				this.type = 0;
				this.action = 0;
				this.position = new UnityEngine.Vector3();
				this.scale = 0.0f;
				this.outline_color = new std_msgs.ColorRGBA();
				this.filled = 0;
				this.fill_color = new std_msgs.ColorRGBA();
				this.lifetime = new SIGVerse.RosBridge.msg_helpers.Duration();
				this.points = new System.Collections.Generic.List<UnityEngine.Vector3>();
				this.outline_colors = new System.Collections.Generic.List<std_msgs.ColorRGBA>();
			}

			public ImageMarker(std_msgs.Header header, string ns, System.Int32 id, System.Int32 type, System.Int32 action, UnityEngine.Vector3 position, float scale, std_msgs.ColorRGBA outline_color, byte filled, std_msgs.ColorRGBA fill_color, SIGVerse.RosBridge.msg_helpers.Duration lifetime, System.Collections.Generic.List<UnityEngine.Vector3>  points, System.Collections.Generic.List<std_msgs.ColorRGBA>  outline_colors)
			{
				this.header = header;
				this.ns = ns;
				this.id = id;
				this.type = type;
				this.action = action;
				this.position = position;
				this.scale = scale;
				this.outline_color = outline_color;
				this.filled = filled;
				this.fill_color = fill_color;
				this.lifetime = lifetime;
				this.points = points;
				this.outline_colors = outline_colors;
			}

			new public static string GetMessageType()
			{
				return "visualization_msgs/ImageMarker";
			}

			new public static string GetMD5Hash()
			{
				return "1de93c67ec8858b831025a08fbf1b35c";
			}
		} // class ImageMarker
	} // namespace visualization_msgs
} // namespace SIGVerse.ROSBridge

