// Generated by gencs from visualization_msgs/InteractiveMarkerControl.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.geometry_msgs;
using SIGVerse.RosBridge.visualization_msgs;

namespace SIGVerse.RosBridge 
{
	namespace visualization_msgs 
	{
		[System.Serializable]
		public class InteractiveMarkerControl : RosMessage
		{
			public string name;
			public UnityEngine.Quaternion orientation;
			public byte orientation_mode;
			public byte interaction_mode;
			public bool always_visible;
			public System.Collections.Generic.List<visualization_msgs.Marker>  markers;
			public bool independent_marker_orientation;
			public string description;

			public const byte INHERIT = 0;
			public const byte FIXED = 1;
			public const byte VIEW_FACING = 2;
			public const byte NONE = 0;
			public const byte MENU = 1;
			public const byte BUTTON = 2;
			public const byte MOVE_AXIS = 3;
			public const byte MOVE_PLANE = 4;
			public const byte ROTATE_AXIS = 5;
			public const byte MOVE_ROTATE = 6;
			public const byte MOVE_3D = 7;
			public const byte ROTATE_3D = 8;
			public const byte MOVE_ROTATE_3D = 9;

			public InteractiveMarkerControl()
			{
				this.name = "";
				this.orientation = new UnityEngine.Quaternion();
				this.orientation_mode = 0;
				this.interaction_mode = 0;
				this.always_visible = false;
				this.markers = new System.Collections.Generic.List<visualization_msgs.Marker>();
				this.independent_marker_orientation = false;
				this.description = "";
			}

			public InteractiveMarkerControl(string name, UnityEngine.Quaternion orientation, byte orientation_mode, byte interaction_mode, bool always_visible, System.Collections.Generic.List<visualization_msgs.Marker>  markers, bool independent_marker_orientation, string description)
			{
				this.name = name;
				this.orientation = orientation;
				this.orientation_mode = orientation_mode;
				this.interaction_mode = interaction_mode;
				this.always_visible = always_visible;
				this.markers = markers;
				this.independent_marker_orientation = independent_marker_orientation;
				this.description = description;
			}

			new public static string GetMessageType()
			{
				return "visualization_msgs/InteractiveMarkerControl";
			}

			new public static string GetMD5Hash()
			{
				return "b3c81e785788195d1840b86c28da1aac";
			}
		} // class InteractiveMarkerControl
	} // namespace visualization_msgs
} // namespace SIGVerse.ROSBridge

