// Generated by gencs from visualization_msgs/InteractiveMarkerInit.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.visualization_msgs;

namespace SIGVerse.RosBridge 
{
	namespace visualization_msgs 
	{
		[System.Serializable]
		public class InteractiveMarkerInit : RosMessage
		{
			public string server_id;
			public System.UInt64 seq_num;
			public System.Collections.Generic.List<visualization_msgs.InteractiveMarker>  markers;


			public InteractiveMarkerInit()
			{
				this.server_id = "";
				this.seq_num = 0;
				this.markers = new System.Collections.Generic.List<visualization_msgs.InteractiveMarker>();
			}

			public InteractiveMarkerInit(string server_id, System.UInt64 seq_num, System.Collections.Generic.List<visualization_msgs.InteractiveMarker>  markers)
			{
				this.server_id = server_id;
				this.seq_num = seq_num;
				this.markers = markers;
			}

			new public static string GetMessageType()
			{
				return "visualization_msgs/InteractiveMarkerInit";
			}

			new public static string GetMD5Hash()
			{
				return "d5f2c5045a72456d228676ab91048734";
			}
		} // class InteractiveMarkerInit
	} // namespace visualization_msgs
} // namespace SIGVerse.ROSBridge

