// Generated by gencs from file nav_msgs/GetPlan.srv
// DO NOT EDIT THIS FILE BY HAND


using SIGVerse.RosBridge.nav_msgs;

namespace SIGVerse.RosBridge 
{
	namespace nav_msgs 
	{
		public class GetPlan : RosBridgeServiceProvider<nav_msgs.GetPlanRequest>
		{
			public GetPlan(string serviceName) : base(serviceName)
			{
				base.type = "nav_msgs/GetPlan";
			}

			public GetPlan(string serviceName, string typeName = "nav_msgs/GetPlan") : base(serviceName, typeName) 
			{
			}
		}
	} // namespace nav_msgs
} // namespace SIGVerse.ROSBridge

