// Generated by gencs from nav_msgs/MapMetaData.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.geometry_msgs;

namespace SIGVerse.RosBridge 
{
	namespace nav_msgs 
	{
		[System.Serializable]
		public class MapMetaData : RosMessage
		{
			public SIGVerse.RosBridge.msg_helpers.Time map_load_time;
			public float resolution;
			public System.UInt32 width;
			public System.UInt32 height;
			public geometry_msgs.Pose origin;


			public MapMetaData()
			{
				this.map_load_time = new SIGVerse.RosBridge.msg_helpers.Time();
				this.resolution = 0.0f;
				this.width = 0;
				this.height = 0;
				this.origin = new geometry_msgs.Pose();
			}

			public MapMetaData(SIGVerse.RosBridge.msg_helpers.Time map_load_time, float resolution, System.UInt32 width, System.UInt32 height, geometry_msgs.Pose origin)
			{
				this.map_load_time = map_load_time;
				this.resolution = resolution;
				this.width = width;
				this.height = height;
				this.origin = origin;
			}

			new public static string GetMessageType()
			{
				return "nav_msgs/MapMetaData";
			}

			new public static string GetMD5Hash()
			{
				return "10cfc8a2818024d3248802c00c95f11b";
			}
		} // class MapMetaData
	} // namespace nav_msgs
} // namespace SIGVerse.ROSBridge

