// Generated by gencs from nav_msgs/SetMap.srv
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.nav_msgs;
using SIGVerse.RosBridge.geometry_msgs;

namespace SIGVerse.RosBridge 
{
	namespace nav_msgs 
	{
		[System.Serializable]
		public class SetMapRequest : ServiceArgs
		{
			public nav_msgs.OccupancyGrid map;
			public geometry_msgs.PoseWithCovarianceStamped initial_pose;


			public SetMapRequest()
			{
				this.map = new nav_msgs.OccupancyGrid();
				this.initial_pose = new geometry_msgs.PoseWithCovarianceStamped();
			}

			public SetMapRequest(nav_msgs.OccupancyGrid map, geometry_msgs.PoseWithCovarianceStamped initial_pose)
			{
				this.map = map;
				this.initial_pose = initial_pose;
			}

			new public static string GetMessageType()
			{
				return "nav_msgs/SetMapRequest";
			}

			new public static string GetMD5Hash()
			{
				return "91149a20d7be299b87c340df8cc94fd4";
			}
		} // class SetMapRequest
	} // namespace nav_msgs
} // namespace SIGVerse.ROSBridge

