// Generated by gencs from actionlib_msgs/msg/GoalStatusArray.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs.msg;
using SIGVerse.RosBridge.actionlib_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace actionlib_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class GoalStatusArray : RosMessage
			{
				public std_msgs.msg.Header header;
				public System.Collections.Generic.List<actionlib_msgs.msg.GoalStatus>  status_list;


				public GoalStatusArray()
				{
					this.header = new std_msgs.msg.Header();
					this.status_list = new System.Collections.Generic.List<actionlib_msgs.msg.GoalStatus>();
				}

				public GoalStatusArray(std_msgs.msg.Header header, System.Collections.Generic.List<actionlib_msgs.msg.GoalStatus>  status_list)
				{
					this.header = header;
					this.status_list = status_list;
				}

				new public static string GetMessageType()
				{
					return "actionlib_msgs/msg/GoalStatusArray";
				}

			} // class GoalStatusArray
		} // namespace msg
	} // namespace actionlib_msgs
} // namespace SIGVerse.RosBridge
