// Generated by gencs from actionlib_msgs/msg/GoalID.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.builtin_interfaces.msg;

namespace SIGVerse.RosBridge 
{
	namespace actionlib_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class GoalID : RosMessage
			{
				public builtin_interfaces.msg.Time stamp;
				public string id;


				public GoalID()
				{
					this.stamp = new builtin_interfaces.msg.Time();
					this.id = "";
				}

				public GoalID(builtin_interfaces.msg.Time stamp, string id)
				{
					this.stamp = stamp;
					this.id = id;
				}

				new public static string GetMessageType()
				{
					return "actionlib_msgs/msg/GoalID";
				}

			} // class GoalID
		} // namespace msg
	} // namespace actionlib_msgs
} // namespace SIGVerse.RosBridge
