// Generated by gencs from actionlib_msgs/msg/GoalStatus.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.actionlib_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace actionlib_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class GoalStatus : RosMessage
			{
				public actionlib_msgs.msg.GoalID goal_id;
				public byte status;
				public string text;

				// Constants:
				public const byte PENDING = 0;
				public const byte ACTIVE = 1;
				public const byte PREEMPTED = 2;
				public const byte SUCCEEDED = 3;
				public const byte ABORTED = 4;
				public const byte REJECTED = 5;
				public const byte PREEMPTING = 6;
				public const byte RECALLING = 7;
				public const byte RECALLED = 8;
				public const byte LOST = 9;

				public GoalStatus()
				{
					this.goal_id = new actionlib_msgs.msg.GoalID();
					this.status = 0;
					this.text = "";
				}

				public GoalStatus(actionlib_msgs.msg.GoalID goal_id, byte status, string text)
				{
					this.goal_id = goal_id;
					this.status = status;
					this.text = text;
				}

				new public static string GetMessageType()
				{
					return "actionlib_msgs/msg/GoalStatus";
				}

			} // class GoalStatus
		} // namespace msg
	} // namespace actionlib_msgs
} // namespace SIGVerse.RosBridge
