// Generated by gencs from diagnostic_msgs/msg/DiagnosticArray.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs.msg;
using SIGVerse.RosBridge.diagnostic_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace diagnostic_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class DiagnosticArray : RosMessage
			{
				public std_msgs.msg.Header header;
				public System.Collections.Generic.List<diagnostic_msgs.msg.DiagnosticStatus>  status;


				public DiagnosticArray()
				{
					this.header = new std_msgs.msg.Header();
					this.status = new System.Collections.Generic.List<diagnostic_msgs.msg.DiagnosticStatus>();
				}

				public DiagnosticArray(std_msgs.msg.Header header, System.Collections.Generic.List<diagnostic_msgs.msg.DiagnosticStatus>  status)
				{
					this.header = header;
					this.status = status;
				}

				new public static string GetMessageType()
				{
					return "diagnostic_msgs/msg/DiagnosticArray";
				}

			} // class DiagnosticArray
		} // namespace msg
	} // namespace diagnostic_msgs
} // namespace SIGVerse.RosBridge
