// Generated by gencs from diagnostic_msgs/msg/KeyValue.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace diagnostic_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class KeyValue : RosMessage
			{
				public string key;
				public string value;


				public KeyValue()
				{
					this.key = "";
					this.value = "";
				}

				public KeyValue(string key, string value)
				{
					this.key = key;
					this.value = value;
				}

				new public static string GetMessageType()
				{
					return "diagnostic_msgs/msg/KeyValue";
				}

			} // class KeyValue
		} // namespace msg
	} // namespace diagnostic_msgs
} // namespace SIGVerse.RosBridge
