// Generated by gencs from shape_msgs/SolidPrimitive.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace shape_msgs 
	{
		[System.Serializable]
		public class SolidPrimitive : RosMessage
		{
			public byte type;
			public System.Collections.Generic.List<double>  dimensions;

			public const byte BOX = 1;
			public const byte SPHERE = 2;
			public const byte CYLINDER = 3;
			public const byte CONE = 4;
			public const byte BOX_X = 0;
			public const byte BOX_Y = 1;
			public const byte BOX_Z = 2;
			public const byte SPHERE_RADIUS = 0;
			public const byte CYLINDER_HEIGHT = 0;
			public const byte CYLINDER_RADIUS = 1;
			public const byte CONE_HEIGHT = 0;
			public const byte CONE_RADIUS = 1;

			public SolidPrimitive()
			{
				this.type = 0;
				this.dimensions = new System.Collections.Generic.List<double>();
			}

			public SolidPrimitive(byte type, System.Collections.Generic.List<double>  dimensions)
			{
				this.type = type;
				this.dimensions = dimensions;
			}

			new public static string GetMessageType()
			{
				return "shape_msgs/SolidPrimitive";
			}

			new public static string GetMD5Hash()
			{
				return "d8f8cbc74c5ff283fca29569ccefb45d";
			}
		} // class SolidPrimitive
	} // namespace shape_msgs
} // namespace SIGVerse.ROSBridge

