// Generated by gencs from turtlesim/SetPen.srv
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace turtlesim 
	{
		[System.Serializable]
		public class SetPenResponse : ServiceResponse
		{


			public SetPenResponse()
			{
			}


			new public static string GetMessageType()
			{
				return "turtlesim/SetPenResponse";
			}

			new public static string GetMD5Hash()
			{
				return "d41d8cd98f00b204e9800998ecf8427e";
			}
		} // class SetPenResponse
	} // namespace turtlesim
} // namespace SIGVerse.ROSBridge

