// Generated by gencs from turtlesim/TeleportRelative.srv
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace turtlesim 
	{
		[System.Serializable]
		public class TeleportRelativeRequest : ServiceArgs
		{
			public float linear;
			public float angular;


			public TeleportRelativeRequest()
			{
				this.linear = 0.0f;
				this.angular = 0.0f;
			}

			public TeleportRelativeRequest(float linear, float angular)
			{
				this.linear = linear;
				this.angular = angular;
			}

			new public static string GetMessageType()
			{
				return "turtlesim/TeleportRelativeRequest";
			}

			new public static string GetMD5Hash()
			{
				return "9d5c2dcd348ac8f76ce2a4307bd63a13";
			}
		} // class TeleportRelativeRequest
	} // namespace turtlesim
} // namespace SIGVerse.ROSBridge

