// Generated by gencs from file turtlesim/TeleportRelative.srv
// DO NOT EDIT THIS FILE BY HAND


using SIGVerse.RosBridge.turtlesim;

namespace SIGVerse.RosBridge 
{
	namespace turtlesim 
	{
		public class TeleportRelative : RosBridgeServiceProvider<turtlesim.TeleportRelativeRequest>
		{
			public TeleportRelative(string serviceName) : base(serviceName)
			{
				base.type = "turtlesim/TeleportRelative";
			}

			public TeleportRelative(string serviceName, string typeName = "turtlesim/TeleportRelative") : base(serviceName, typeName) 
			{
			}
		}
	} // namespace turtlesim
} // namespace SIGVerse.ROSBridge

