// Generated by gencs from sensor_msgs/Joy.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs;

namespace SIGVerse.RosBridge 
{
	namespace sensor_msgs 
	{
		[System.Serializable]
		public class Joy : RosMessage
		{
			public std_msgs.Header header;
			public System.Collections.Generic.List<float>  axes;
			public System.Collections.Generic.List<System.Int32>  buttons;


			public Joy()
			{
				this.header = new std_msgs.Header();
				this.axes = new System.Collections.Generic.List<float>();
				this.buttons = new System.Collections.Generic.List<System.Int32>();
			}

			public Joy(std_msgs.Header header, System.Collections.Generic.List<float>  axes, System.Collections.Generic.List<System.Int32>  buttons)
			{
				this.header = header;
				this.axes = axes;
				this.buttons = buttons;
			}

			new public static string GetMessageType()
			{
				return "sensor_msgs/Joy";
			}

			new public static string GetMD5Hash()
			{
				return "5a9ea5f83505693b71e785041e67a8bb";
			}
		} // class Joy
	} // namespace sensor_msgs
} // namespace SIGVerse.ROSBridge

