// Generated by gencs from sensor_msgs/MagneticField.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs;
using SIGVerse.RosBridge.geometry_msgs;

namespace SIGVerse.RosBridge 
{
	namespace sensor_msgs 
	{
		[System.Serializable]
		public class MagneticField : RosMessage
		{
			public std_msgs.Header header;
			public UnityEngine.Vector3 magnetic_field;
			public double[]  magnetic_field_covariance;


			public MagneticField()
			{
				this.header = new std_msgs.Header();
				this.magnetic_field = new UnityEngine.Vector3();
				this.magnetic_field_covariance = new double[9];
			}

			public MagneticField(std_msgs.Header header, UnityEngine.Vector3 magnetic_field, double[]  magnetic_field_covariance)
			{
				this.header = header;
				this.magnetic_field = magnetic_field;
				this.magnetic_field_covariance = magnetic_field_covariance;
			}

			new public static string GetMessageType()
			{
				return "sensor_msgs/MagneticField";
			}

			new public static string GetMD5Hash()
			{
				return "2f3b0b43eed0c9501de0fa3ff89a45aa";
			}
		} // class MagneticField
	} // namespace sensor_msgs
} // namespace SIGVerse.ROSBridge

