// Generated by gencs from sensor_msgs/SetCameraInfo.srv
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace sensor_msgs 
	{
		[System.Serializable]
		public class SetCameraInfoResponse : ServiceResponse
		{
			public bool success;
			public string status_message;


			public SetCameraInfoResponse()
			{
				this.success = false;
				this.status_message = "";
			}

			public SetCameraInfoResponse(bool success, string status_message)
			{
				this.success = success;
				this.status_message = status_message;
			}

			new public static string GetMessageType()
			{
				return "sensor_msgs/SetCameraInfoResponse";
			}

			new public static string GetMD5Hash()
			{
				return "2ec6f3eff0161f4257b808b12bc830c2";
			}
		} // class SetCameraInfoResponse
	} // namespace sensor_msgs
} // namespace SIGVerse.ROSBridge

