// Generated by gencs from sensor_msgs/SetCameraInfo.srv
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.sensor_msgs;

namespace SIGVerse.RosBridge 
{
	namespace sensor_msgs 
	{
		[System.Serializable]
		public class SetCameraInfoRequest : ServiceArgs
		{
			public sensor_msgs.CameraInfo camera_info;


			public SetCameraInfoRequest()
			{
				this.camera_info = new sensor_msgs.CameraInfo();
			}

			public SetCameraInfoRequest(sensor_msgs.CameraInfo camera_info)
			{
				this.camera_info = camera_info;
			}

			new public static string GetMessageType()
			{
				return "sensor_msgs/SetCameraInfoRequest";
			}

			new public static string GetMD5Hash()
			{
				return "ee34be01fdeee563d0d99cd594d5581d";
			}
		} // class SetCameraInfoRequest
	} // namespace sensor_msgs
} // namespace SIGVerse.ROSBridge

