// Generated by gencs from geometry_msgs/PointStamped.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.ROSBridge;
using UnityEngine;

using SIGVerse.ROSBridge.std_msgs;
using SIGVerse.ROSBridge.geometry_msgs;

namespace SIGVerse.ROSBridge 
{
	namespace geometry_msgs 
	{
		[System.Serializable]
		public class PointStamped : ROSMessage
		{
			public std_msgs.Header header;
			public UnityEngine.Vector3 point;


			public PointStamped()
			{
				this.header = new std_msgs.Header();
				this.point = new UnityEngine.Vector3();
			}

			public PointStamped(std_msgs.Header header, UnityEngine.Vector3 point)
			{
				this.header = header;
				this.point = point;
			}

			new public static string GetMessageType()
			{
				return "geometry_msgs/PointStamped";
			}

			new public static string GetMD5Hash()
			{
				return "c63aecb41bfdfd6b7e1fac37c7cbe7bf";
			}
		} // class PointStamped
	} // namespace geometry_msgs
} // namespace SIGVerse.ROSBridge

