// Generated by gencs from geometry_msgs/Point32.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace geometry_msgs 
	{
		[System.Serializable]
		public class Point32 : RosMessage
		{
			public float x;
			public float y;
			public float z;


			public Point32()
			{
				this.x = 0.0f;
				this.y = 0.0f;
				this.z = 0.0f;
			}

			public Point32(float x, float y, float z)
			{
				this.x = x;
				this.y = y;
				this.z = z;
			}

			new public static string GetMessageType()
			{
				return "geometry_msgs/Point32";
			}

			new public static string GetMD5Hash()
			{
				return "cc153912f1453b708d221682bc23d9ac";
			}
		} // class Point32
	} // namespace geometry_msgs
} // namespace SIGVerse.ROSBridge

