// Generated by gencs from geometry_msgs/PolygonStamped.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs;
using SIGVerse.RosBridge.geometry_msgs;

namespace SIGVerse.RosBridge 
{
	namespace geometry_msgs 
	{
		[System.Serializable]
		public class PolygonStamped : RosMessage
		{
			public std_msgs.Header header;
			public geometry_msgs.Polygon polygon;


			public PolygonStamped()
			{
				this.header = new std_msgs.Header();
				this.polygon = new geometry_msgs.Polygon();
			}

			public PolygonStamped(std_msgs.Header header, geometry_msgs.Polygon polygon)
			{
				this.header = header;
				this.polygon = polygon;
			}

			new public static string GetMessageType()
			{
				return "geometry_msgs/PolygonStamped";
			}

			new public static string GetMD5Hash()
			{
				return "c6be8f7dc3bee7fe9e8d296070f53340";
			}
		} // class PolygonStamped
	} // namespace geometry_msgs
} // namespace SIGVerse.ROSBridge

