// Generated by gencs from geometry_msgs/PoseArray.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.ROSBridge;
using UnityEngine;

using SIGVerse.ROSBridge.std_msgs;
using SIGVerse.ROSBridge.geometry_msgs;

namespace SIGVerse.ROSBridge 
{
	namespace geometry_msgs 
	{
		[System.Serializable]
		public class PoseArray : ROSMessage
		{
			public std_msgs.Header header;
			public System.Collections.Generic.List<geometry_msgs.Pose>  poses;


			public PoseArray()
			{
				this.header = new std_msgs.Header();
				this.poses = new System.Collections.Generic.List<geometry_msgs.Pose>();
			}

			public PoseArray(std_msgs.Header header, System.Collections.Generic.List<geometry_msgs.Pose>  poses)
			{
				this.header = header;
				this.poses = poses;
			}

			new public static string GetMessageType()
			{
				return "geometry_msgs/PoseArray";
			}

			new public static string GetMD5Hash()
			{
				return "916c28c5764443f268b296bb671b9d97";
			}
		} // class PoseArray
	} // namespace geometry_msgs
} // namespace SIGVerse.ROSBridge

