// Generated by gencs from geometry_msgs/Quaternion.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace geometry_msgs 
	{
		[System.Serializable]
		public class Quaternion : RosMessage
		{
			public double x;
			public double y;
			public double z;
			public double w;


			public Quaternion()
			{
				this.x = 0.0;
				this.y = 0.0;
				this.z = 0.0;
				this.w = 0.0;
			}

			public Quaternion(double x, double y, double z, double w)
			{
				this.x = x;
				this.y = y;
				this.z = z;
				this.w = w;
			}

			new public static string GetMessageType()
			{
				return "geometry_msgs/Quaternion";
			}

			new public static string GetMD5Hash()
			{
				return "a779879fadf0160734f906b8c19c7004";
			}
		} // class Quaternion
	} // namespace geometry_msgs
} // namespace SIGVerse.ROSBridge

