// Generated by gencs from geometry_msgs/QuaternionStamped.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.ROSBridge;
using UnityEngine;

using SIGVerse.ROSBridge.std_msgs;
using SIGVerse.ROSBridge.geometry_msgs;

namespace SIGVerse.ROSBridge 
{
	namespace geometry_msgs 
	{
		[System.Serializable]
		public class QuaternionStamped : ROSMessage
		{
			public std_msgs.Header header;
			public UnityEngine.Quaternion quaternion;


			public QuaternionStamped()
			{
				this.header = new std_msgs.Header();
				this.quaternion = new UnityEngine.Quaternion();
			}

			public QuaternionStamped(std_msgs.Header header, UnityEngine.Quaternion quaternion)
			{
				this.header = header;
				this.quaternion = quaternion;
			}

			new public static string GetMessageType()
			{
				return "geometry_msgs/QuaternionStamped";
			}

			new public static string GetMD5Hash()
			{
				return "e57f1e547e0e1fd13504588ffc8334e2";
			}
		} // class QuaternionStamped
	} // namespace geometry_msgs
} // namespace SIGVerse.ROSBridge

