// Generated by gencs from geometry_msgs/Transform.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.geometry_msgs;

namespace SIGVerse.RosBridge 
{
	namespace geometry_msgs 
	{
		[System.Serializable]
		public class Transform : RosMessage
		{
			public UnityEngine.Vector3 translation;
			public UnityEngine.Quaternion rotation;


			public Transform()
			{
				this.translation = new UnityEngine.Vector3();
				this.rotation = new UnityEngine.Quaternion();
			}

			public Transform(UnityEngine.Vector3 translation, UnityEngine.Quaternion rotation)
			{
				this.translation = translation;
				this.rotation = rotation;
			}

			new public static string GetMessageType()
			{
				return "geometry_msgs/Transform";
			}

			new public static string GetMD5Hash()
			{
				return "ac9eff44abf714214112b05d54a3cf9b";
			}
		} // class Transform
	} // namespace geometry_msgs
} // namespace SIGVerse.ROSBridge

