// Generated by gencs from std_msgs/Byte.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace std_msgs 
	{
		[System.Serializable]
		public class Byte : RosMessage
		{
			public sbyte data;


			public Byte()
			{
				this.data = 0;
			}

			public Byte(sbyte data)
			{
				this.data = data;
			}

			new public static string GetMessageType()
			{
				return "std_msgs/Byte";
			}

			new public static string GetMD5Hash()
			{
				return "ad736a2e8818154c487bb80fe42ce43b";
			}
		} // class Byte
	} // namespace std_msgs
} // namespace SIGVerse.ROSBridge

