// Generated by gencs from std_msgs/Float32MultiArray.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs;

namespace SIGVerse.RosBridge 
{
	namespace std_msgs 
	{
		[System.Serializable]
		public class Float32MultiArray : RosMessage
		{
			public std_msgs.MultiArrayLayout layout;
			public System.Collections.Generic.List<float>  data;


			public Float32MultiArray()
			{
				this.layout = new std_msgs.MultiArrayLayout();
				this.data = new System.Collections.Generic.List<float>();
			}

			public Float32MultiArray(std_msgs.MultiArrayLayout layout, System.Collections.Generic.List<float>  data)
			{
				this.layout = layout;
				this.data = data;
			}

			new public static string GetMessageType()
			{
				return "std_msgs/Float32MultiArray";
			}

			new public static string GetMD5Hash()
			{
				return "6a40e0ffa6a17a503ac3f8616991b1f6";
			}
		} // class Float32MultiArray
	} // namespace std_msgs
} // namespace SIGVerse.ROSBridge

