// Generated by gencs from std_msgs/Header.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.ROSBridge;
using UnityEngine;


namespace SIGVerse.ROSBridge 
{
	namespace std_msgs 
	{
		[System.Serializable]
		public class Header : ROSMessage
		{
			private static readonly DateTime UnixEpoch = new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc);

			public System.UInt32 seq;
			public SIGVerse.ROSBridge.msg_helpers.Time stamp;
			public string frame_id;


			public Header()
			{
				this.seq = 0;
				this.stamp = new SIGVerse.ROSBridge.msg_helpers.Time();
				this.frame_id = "";
			}

			public Header(System.UInt32 seq, SIGVerse.ROSBridge.msg_helpers.Time stamp, string frame_id)
			{
				this.seq = seq;
				this.stamp = stamp;
				this.frame_id = frame_id;
			}

			// Added by hand
			public void Update()
			{
				this.seq++;

				if(SIGVerse.Common.ConfigManager.Instance.configInfo.setUpRosTimestamp)
				{
					TimeSpan epochTime = DateTime.Now.ToUniversalTime() - UnixEpoch;
					this.stamp.secs = (int)epochTime.TotalSeconds;
					this.stamp.nsecs = epochTime.Milliseconds * 1000 * 1000;
				}
			}

			new public static string GetMessageType()
			{
				return "std_msgs/Header";
			}

			new public static string GetMD5Hash()
			{
				return "2176decaecbce78abc3b96ef049fabed";
			}
		} // class Header
	} // namespace std_msgs
} // namespace SIGVerse.ROSBridge

