// Generated by gencs from std_msgs/Int16MultiArray.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs;

namespace SIGVerse.RosBridge 
{
	namespace std_msgs 
	{
		[System.Serializable]
		public class Int16MultiArray : RosMessage
		{
			public std_msgs.MultiArrayLayout layout;
			public System.Collections.Generic.List<System.Int16>  data;


			public Int16MultiArray()
			{
				this.layout = new std_msgs.MultiArrayLayout();
				this.data = new System.Collections.Generic.List<System.Int16>();
			}

			public Int16MultiArray(std_msgs.MultiArrayLayout layout, System.Collections.Generic.List<System.Int16>  data)
			{
				this.layout = layout;
				this.data = data;
			}

			new public static string GetMessageType()
			{
				return "std_msgs/Int16MultiArray";
			}

			new public static string GetMD5Hash()
			{
				return "d9338d7f523fcb692fae9d0a0e9f067c";
			}
		} // class Int16MultiArray
	} // namespace std_msgs
} // namespace SIGVerse.ROSBridge

