// Generated by gencs from std_msgs/Int32.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace std_msgs 
	{
		[System.Serializable]
		public class Int32 : RosMessage
		{
			public System.Int32 data;


			public Int32()
			{
				this.data = 0;
			}

			public Int32(System.Int32 data)
			{
				this.data = data;
			}

			new public static string GetMessageType()
			{
				return "std_msgs/Int32";
			}

			new public static string GetMD5Hash()
			{
				return "da5909fbe378aeaf85e547e830cc1bb7";
			}
		} // class Int32
	} // namespace std_msgs
} // namespace SIGVerse.ROSBridge

