// Generated by gencs from std_msgs/Time.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace std_msgs 
	{
		[System.Serializable]
		public class Time : RosMessage
		{
			public SIGVerse.RosBridge.msg_helpers.Time data;


			public Time()
			{
				this.data = new SIGVerse.RosBridge.msg_helpers.Time();
			}

			public Time(SIGVerse.RosBridge.msg_helpers.Time data)
			{
				this.data = data;
			}

			new public static string GetMessageType()
			{
				return "std_msgs/Time";
			}

			new public static string GetMD5Hash()
			{
				return "cd7166c74c552c311fbcc2fe5a7bc289";
			}
		} // class Time
	} // namespace std_msgs
} // namespace SIGVerse.ROSBridge

