// Generated by gencs from std_msgs/UInt32.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace std_msgs 
	{
		[System.Serializable]
		public class UInt32 : RosMessage
		{
			public System.UInt32 data;


			public UInt32()
			{
				this.data = 0;
			}

			public UInt32(System.UInt32 data)
			{
				this.data = data;
			}

			new public static string GetMessageType()
			{
				return "std_msgs/UInt32";
			}

			new public static string GetMD5Hash()
			{
				return "304a39449588c7f8ce2df6e8001c5fce";
			}
		} // class UInt32
	} // namespace std_msgs
} // namespace SIGVerse.ROSBridge

