// Generated by gencs from nav_msgs/GetMap.srv
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.nav_msgs;

namespace SIGVerse.RosBridge 
{
	namespace nav_msgs 
	{
		[System.Serializable]
		public class GetMapResponse : ServiceResponse
		{
			public nav_msgs.OccupancyGrid map;


			public GetMapResponse()
			{
				this.map = new nav_msgs.OccupancyGrid();
			}

			public GetMapResponse(nav_msgs.OccupancyGrid map)
			{
				this.map = map;
			}

			new public static string GetMessageType()
			{
				return "nav_msgs/GetMapResponse";
			}

			new public static string GetMD5Hash()
			{
				return "6cdd0a18e0aff5b0a3ca2326a89b54ff";
			}
		} // class GetMapResponse
	} // namespace nav_msgs
} // namespace SIGVerse.ROSBridge

