// Generated by gencs from nav_msgs/GetPlan.srv
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.geometry_msgs;

namespace SIGVerse.RosBridge 
{
	namespace nav_msgs 
	{
		[System.Serializable]
		public class GetPlanRequest : ServiceArgs
		{
			public geometry_msgs.PoseStamped start;
			public geometry_msgs.PoseStamped goal;
			public float tolerance;


			public GetPlanRequest()
			{
				this.start = new geometry_msgs.PoseStamped();
				this.goal = new geometry_msgs.PoseStamped();
				this.tolerance = 0.0f;
			}

			public GetPlanRequest(geometry_msgs.PoseStamped start, geometry_msgs.PoseStamped goal, float tolerance)
			{
				this.start = start;
				this.goal = goal;
				this.tolerance = tolerance;
			}

			new public static string GetMessageType()
			{
				return "nav_msgs/GetPlanRequest";
			}

			new public static string GetMD5Hash()
			{
				return "e25a43e0752bcca599a8c2eef8282df8";
			}
		} // class GetPlanRequest
	} // namespace nav_msgs
} // namespace SIGVerse.ROSBridge

