// Generated by gencs from nav_msgs/OccupancyGrid.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs;
using SIGVerse.RosBridge.nav_msgs;

namespace SIGVerse.RosBridge 
{
	namespace nav_msgs 
	{
		[System.Serializable]
		public class OccupancyGrid : RosMessage
		{
			public std_msgs.Header header;
			public nav_msgs.MapMetaData info;
			public System.Collections.Generic.List<sbyte>  data;


			public OccupancyGrid()
			{
				this.header = new std_msgs.Header();
				this.info = new nav_msgs.MapMetaData();
				this.data = new System.Collections.Generic.List<sbyte>();
			}

			public OccupancyGrid(std_msgs.Header header, nav_msgs.MapMetaData info, System.Collections.Generic.List<sbyte>  data)
			{
				this.header = header;
				this.info = info;
				this.data = data;
			}

			new public static string GetMessageType()
			{
				return "nav_msgs/OccupancyGrid";
			}

			new public static string GetMD5Hash()
			{
				return "3381f2d731d4076ec5c71b0759edbe4e";
			}
		} // class OccupancyGrid
	} // namespace nav_msgs
} // namespace SIGVerse.ROSBridge

