// Generated by gencs from file nav_msgs/SetMap.srv
// DO NOT EDIT THIS FILE BY HAND


using SIGVerse.RosBridge.nav_msgs;

namespace SIGVerse.RosBridge 
{
	namespace nav_msgs 
	{
		public class SetMap : RosBridgeServiceProvider<nav_msgs.SetMapRequest>
		{
			public SetMap(string serviceName) : base(serviceName)
			{
				base.type = "nav_msgs/SetMap";
			}

			public SetMap(string serviceName, string typeName = "nav_msgs/SetMap") : base(serviceName, typeName) 
			{
			}
		}
	} // namespace nav_msgs
} // namespace SIGVerse.ROSBridge

