// Generated by gencs from sensor_msgs/srv/SetCameraInfo.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace sensor_msgs 
	{
		namespace srv 
		{
			public class SetCameraInfo : RosBridgeServiceProvider<SetCameraInfo_Request>
			{

				public SetCameraInfo(string serviceName) : base(serviceName)
				{
					base.type = "sensor_msgs/srv/SetCameraInfo";
				}

				public SetCameraInfo(string serviceName, string serviceType = "sensor_msgs/srv/SetCameraInfo") : base(serviceName, serviceType) {}

			} // class SetCameraInfo

			[System.Serializable]
			public class SetCameraInfo_Request : ServiceArgs
			{
				public sensor_msgs.msg.CameraInfo camera_info;


				public SetCameraInfo_Request()
				{
					this.camera_info = new sensor_msgs.msg.CameraInfo();
				}

				public SetCameraInfo_Request(sensor_msgs.msg.CameraInfo camera_info)
				{
					this.camera_info = camera_info;
				}

				new public static string GetMessageType()
				{
					return "sensor_msgs/srv/SetCameraInfo_Request";
				}

			} // class SetCameraInfo_Request

			[System.Serializable]
			public class SetCameraInfo_Response : ServiceResponse
			{
				public bool success;
				public string status_message;


				public SetCameraInfo_Response()
				{
					this.success = false;
					this.status_message = "";
				}

				public SetCameraInfo_Response(bool success, string status_message)
				{
					this.success = success;
					this.status_message = status_message;
				}

				new public static string GetMessageType()
				{
					return "sensor_msgs/srv/SetCameraInfo_Response";
				}

			} // class SetCameraInfo_Response
		} // namespace srv
	} // namespace sensor_msgs
} // namespace SIGVerse.RosBridge
