// Generated by gencs from nav_msgs/GetMapGoal.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.ROSBridge;
using UnityEngine;


namespace SIGVerse.ROSBridge 
{
	namespace nav_msgs 
	{
		[System.Serializable]
		public class GetMapGoal : ROSMessage
		{


			public GetMapGoal()
			{
			}


			new public static string GetMessageType()
			{
				return "nav_msgs/GetMapGoal";
			}

			new public static string GetMD5Hash()
			{
				return "d41d8cd98f00b204e9800998ecf8427e";
			}
		} // class GetMapGoal
	} // namespace nav_msgs
} // namespace SIGVerse.ROSBridge

