// Generated by gencs from nav_msgs/GetMap.srv
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace nav_msgs 
	{
		[System.Serializable]
		public class GetMapRequest : ServiceArgs
		{


			public GetMapRequest()
			{
			}


			new public static string GetMessageType()
			{
				return "nav_msgs/GetMapRequest";
			}

			new public static string GetMD5Hash()
			{
				return "d41d8cd98f00b204e9800998ecf8427e";
			}
		} // class GetMapRequest
	} // namespace nav_msgs
} // namespace SIGVerse.ROSBridge

