// Generated by gencs from file nav_msgs/GetMap.srv
// DO NOT EDIT THIS FILE BY HAND


using SIGVerse.ROSBridge.nav_msgs;

namespace SIGVerse.ROSBridge 
{
	namespace nav_msgs 
	{
		public class GetMap : ROSBridgeServiceProvider<nav_msgs.GetMapRequest>
		{
			public GetMap(string serviceName) : base(serviceName)
			{
				base.type = "nav_msgs/GetMap";
			}

			public GetMap(string serviceName, string typeName = "nav_msgs/GetMap") : base(serviceName, typeName) 
			{
			}
		}
	} // namespace nav_msgs
} // namespace SIGVerse.ROSBridge

