// Generated by gencs from geometry_msgs/AccelStamped.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs;
using SIGVerse.RosBridge.geometry_msgs;

namespace SIGVerse.RosBridge 
{
	namespace geometry_msgs 
	{
		[System.Serializable]
		public class AccelStamped : RosMessage
		{
			public std_msgs.Header header;
			public geometry_msgs.Accel accel;


			public AccelStamped()
			{
				this.header = new std_msgs.Header();
				this.accel = new geometry_msgs.Accel();
			}

			public AccelStamped(std_msgs.Header header, geometry_msgs.Accel accel)
			{
				this.header = header;
				this.accel = accel;
			}

			new public static string GetMessageType()
			{
				return "geometry_msgs/AccelStamped";
			}

			new public static string GetMD5Hash()
			{
				return "d8a98a5d81351b6eb0578c78557e7659";
			}
		} // class AccelStamped
	} // namespace geometry_msgs
} // namespace SIGVerse.ROSBridge

