// Generated by gencs from geometry_msgs/AccelWithCovariance.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.geometry_msgs;

namespace SIGVerse.RosBridge 
{
	namespace geometry_msgs 
	{
		[System.Serializable]
		public class AccelWithCovariance : RosMessage
		{
			public geometry_msgs.Accel accel;
			public double[]  covariance;


			public AccelWithCovariance()
			{
				this.accel = new geometry_msgs.Accel();
				this.covariance = new double[36];
			}

			public AccelWithCovariance(geometry_msgs.Accel accel, double[]  covariance)
			{
				this.accel = accel;
				this.covariance = covariance;
			}

			new public static string GetMessageType()
			{
				return "geometry_msgs/AccelWithCovariance";
			}

			new public static string GetMD5Hash()
			{
				return "ad5a718d699c6be72a02b8d6a139f334";
			}
		} // class AccelWithCovariance
	} // namespace geometry_msgs
} // namespace SIGVerse.ROSBridge

