// Generated by gencs from geometry_msgs/InertiaStamped.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs;
using SIGVerse.RosBridge.geometry_msgs;

namespace SIGVerse.RosBridge 
{
	namespace geometry_msgs 
	{
		[System.Serializable]
		public class InertiaStamped : RosMessage
		{
			public std_msgs.Header header;
			public geometry_msgs.Inertia inertia;


			public InertiaStamped()
			{
				this.header = new std_msgs.Header();
				this.inertia = new geometry_msgs.Inertia();
			}

			public InertiaStamped(std_msgs.Header header, geometry_msgs.Inertia inertia)
			{
				this.header = header;
				this.inertia = inertia;
			}

			new public static string GetMessageType()
			{
				return "geometry_msgs/InertiaStamped";
			}

			new public static string GetMD5Hash()
			{
				return "ddee48caeab5a966c5e8d166654a9ac7";
			}
		} // class InertiaStamped
	} // namespace geometry_msgs
} // namespace SIGVerse.ROSBridge

