// Generated by gencs from geometry_msgs/Pose2D.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace geometry_msgs 
	{
		[System.Serializable]
		public class Pose2D : RosMessage
		{
			public double x;
			public double y;
			public double theta;


			public Pose2D()
			{
				this.x = 0.0;
				this.y = 0.0;
				this.theta = 0.0;
			}

			public Pose2D(double x, double y, double theta)
			{
				this.x = x;
				this.y = y;
				this.theta = theta;
			}

			new public static string GetMessageType()
			{
				return "geometry_msgs/Pose2D";
			}

			new public static string GetMD5Hash()
			{
				return "938fa65709584ad8e77d238529be13b8";
			}
		} // class Pose2D
	} // namespace geometry_msgs
} // namespace SIGVerse.ROSBridge

