// Generated by gencs from geometry_msgs/PoseWithCovariance.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.geometry_msgs;

namespace SIGVerse.RosBridge 
{
	namespace geometry_msgs 
	{
		[System.Serializable]
		public class PoseWithCovariance : RosMessage
		{
			public geometry_msgs.Pose pose;
			public double[]  covariance;


			public PoseWithCovariance()
			{
				this.pose = new geometry_msgs.Pose();
				this.covariance = new double[36];
			}

			public PoseWithCovariance(geometry_msgs.Pose pose, double[]  covariance)
			{
				this.pose = pose;
				this.covariance = covariance;
			}

			new public static string GetMessageType()
			{
				return "geometry_msgs/PoseWithCovariance";
			}

			new public static string GetMD5Hash()
			{
				return "c23e848cf1b7533a8d7c259073a97e6f";
			}
		} // class PoseWithCovariance
	} // namespace geometry_msgs
} // namespace SIGVerse.ROSBridge

