// Generated by gencs from turtlesim/Color.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace turtlesim 
	{
		[System.Serializable]
		public class Color : RosMessage
		{
			public byte r;
			public byte g;
			public byte b;


			public Color()
			{
				this.r = 0;
				this.g = 0;
				this.b = 0;
			}

			public Color(byte r, byte g, byte b)
			{
				this.r = r;
				this.g = g;
				this.b = b;
			}

			new public static string GetMessageType()
			{
				return "turtlesim/Color";
			}

			new public static string GetMD5Hash()
			{
				return "353891e354491c51aabe32df673fb446";
			}
		} // class Color
	} // namespace turtlesim
} // namespace SIGVerse.ROSBridge

