// Generated by gencs from turtlesim/Kill.srv
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace turtlesim 
	{
		[System.Serializable]
		public class KillResponse : ServiceResponse
		{


			public KillResponse()
			{
			}


			new public static string GetMessageType()
			{
				return "turtlesim/KillResponse";
			}

			new public static string GetMD5Hash()
			{
				return "d41d8cd98f00b204e9800998ecf8427e";
			}
		} // class KillResponse
	} // namespace turtlesim
} // namespace SIGVerse.ROSBridge

