// Generated by gencs from turtlesim/Kill.srv
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace turtlesim 
	{
		[System.Serializable]
		public class KillRequest : ServiceArgs
		{
			public string name;


			public KillRequest()
			{
				this.name = "";
			}

			public KillRequest(string name)
			{
				this.name = name;
			}

			new public static string GetMessageType()
			{
				return "turtlesim/KillRequest";
			}

			new public static string GetMD5Hash()
			{
				return "c1f3d28f1b044c871e6eff2e9fc3c667";
			}
		} // class KillRequest
	} // namespace turtlesim
} // namespace SIGVerse.ROSBridge

