// Generated by gencs from turtlesim/Spawn.srv
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace turtlesim 
	{
		[System.Serializable]
		public class SpawnRequest : ServiceArgs
		{
			public float x;
			public float y;
			public float theta;
			public string name;


			public SpawnRequest()
			{
				this.x = 0.0f;
				this.y = 0.0f;
				this.theta = 0.0f;
				this.name = "";
			}

			public SpawnRequest(float x, float y, float theta, string name)
			{
				this.x = x;
				this.y = y;
				this.theta = theta;
				this.name = name;
			}

			new public static string GetMessageType()
			{
				return "turtlesim/SpawnRequest";
			}

			new public static string GetMD5Hash()
			{
				return "57f001c49ab7b11d699f8606c1f4f7ff";
			}
		} // class SpawnRequest
	} // namespace turtlesim
} // namespace SIGVerse.ROSBridge

