// Generated by gencs from turtlesim/Spawn.srv
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace turtlesim 
	{
		[System.Serializable]
		public class SpawnResponse : ServiceResponse
		{
			public string name;


			public SpawnResponse()
			{
				this.name = "";
			}

			public SpawnResponse(string name)
			{
				this.name = name;
			}

			new public static string GetMessageType()
			{
				return "turtlesim/SpawnResponse";
			}

			new public static string GetMD5Hash()
			{
				return "c1f3d28f1b044c871e6eff2e9fc3c667";
			}
		} // class SpawnResponse
	} // namespace turtlesim
} // namespace SIGVerse.ROSBridge

