//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#if SIGVERSE_STEAMVR
namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_sigverse : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Vector2 Move
        {
            get
            {
                return SteamVR_Actions.sigverse_Move;
            }
        }
        
        public virtual SteamVR_Action_Single SqueezeIndex
        {
            get
            {
                return SteamVR_Actions.sigverse_SqueezeIndex;
            }
        }
        
        public virtual SteamVR_Action_Single SqueezeMiddle
        {
            get
            {
                return SteamVR_Actions.sigverse_SqueezeMiddle;
            }
        }
        
        public virtual SteamVR_Action_Single Squeeze
        {
            get
            {
                return SteamVR_Actions.sigverse_Squeeze;
            }
        }
        
        public virtual SteamVR_Action_Boolean PressNearButton
        {
            get
            {
                return SteamVR_Actions.sigverse_PressNearButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean PressFarButton
        {
            get
            {
                return SteamVR_Actions.sigverse_PressFarButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean PressThumbstick
        {
            get
            {
                return SteamVR_Actions.sigverse_PressThumbstick;
            }
        }
        
        public virtual SteamVR_Action_Boolean PressIndex
        {
            get
            {
                return SteamVR_Actions.sigverse_PressIndex;
            }
        }
        
        public virtual SteamVR_Action_Boolean PressMiddle
        {
            get
            {
                return SteamVR_Actions.sigverse_PressMiddle;
            }
        }
        
        public virtual SteamVR_Action_Boolean ThumbstickUp
        {
            get
            {
                return SteamVR_Actions.sigverse_ThumbstickUp;
            }
        }
        
        public virtual SteamVR_Action_Boolean ThumbstickDown
        {
            get
            {
                return SteamVR_Actions.sigverse_ThumbstickDown;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.sigverse_Haptic;
            }
        }
    }
}
#endif
