// Generated by gencs from file diagnostic_msgs/AddDiagnostics.srv
// DO NOT EDIT THIS FILE BY HAND


using SIGVerse.RosBridge.diagnostic_msgs;

namespace SIGVerse.RosBridge 
{
	namespace diagnostic_msgs 
	{
		public class AddDiagnostics : RosBridgeServiceProvider<diagnostic_msgs.AddDiagnosticsRequest>
		{
			public AddDiagnostics(string serviceName) : base(serviceName)
			{
				base.type = "diagnostic_msgs/AddDiagnostics";
			}

			public AddDiagnostics(string serviceName, string typeName = "diagnostic_msgs/AddDiagnostics") : base(serviceName, typeName) 
			{
			}
		}
	} // namespace diagnostic_msgs
} // namespace SIGVerse.ROSBridge

