// Generated by gencs from diagnostic_msgs/DiagnosticStatus.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.diagnostic_msgs;

namespace SIGVerse.RosBridge 
{
	namespace diagnostic_msgs 
	{
		[System.Serializable]
		public class DiagnosticStatus : RosMessage
		{
			public sbyte level;
			public string name;
			public string message;
			public string hardware_id;
			public System.Collections.Generic.List<diagnostic_msgs.KeyValue>  values;

			public const sbyte OK = 0;
			public const sbyte WARN = 1;
			public const sbyte ERROR = 2;
			public const sbyte STALE = 3;

			public DiagnosticStatus()
			{
				this.level = 0;
				this.name = "";
				this.message = "";
				this.hardware_id = "";
				this.values = new System.Collections.Generic.List<diagnostic_msgs.KeyValue>();
			}

			public DiagnosticStatus(sbyte level, string name, string message, string hardware_id, System.Collections.Generic.List<diagnostic_msgs.KeyValue>  values)
			{
				this.level = level;
				this.name = name;
				this.message = message;
				this.hardware_id = hardware_id;
				this.values = values;
			}

			new public static string GetMessageType()
			{
				return "diagnostic_msgs/DiagnosticStatus";
			}

			new public static string GetMD5Hash()
			{
				return "d0ce08bc6e5ba34c7754f563a9cabaf1";
			}
		} // class DiagnosticStatus
	} // namespace diagnostic_msgs
} // namespace SIGVerse.ROSBridge

