// Generated by gencs from file diagnostic_msgs/SelfTest.srv
// DO NOT EDIT THIS FILE BY HAND


using SIGVerse.ROSBridge.diagnostic_msgs;

namespace SIGVerse.ROSBridge 
{
	namespace diagnostic_msgs 
	{
		public class SelfTest : ROSBridgeServiceProvider<diagnostic_msgs.SelfTestRequest>
		{
			public SelfTest(string serviceName) : base(serviceName)
			{
				base.type = "diagnostic_msgs/SelfTest";
			}

			public SelfTest(string serviceName, string typeName = "diagnostic_msgs/SelfTest") : base(serviceName, typeName) 
			{
			}
		}
	} // namespace diagnostic_msgs
} // namespace SIGVerse.ROSBridge

