// Generated by gencs from sensor_msgs/msg/CameraInfo.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs.msg;
using SIGVerse.RosBridge.sensor_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace sensor_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class CameraInfoForSIGVerseBridge : RosMessage
			{
				public std_msgs.msg.Header header;
				public System.UInt32 height;
				public System.UInt32 width;
				public string distortion_model;
				public double[]  d;
				public double[]  k;
				public double[]  r;
				public double[]  p;
				public System.UInt32 binning_x;
				public System.UInt32 binning_y;
				public sensor_msgs.msg.RegionOfInterest roi;


				public CameraInfoForSIGVerseBridge()
				{
					this.header = new std_msgs.msg.Header();
					this.height = 0;
					this.width = 0;
					this.distortion_model = "";
					this.d = new double[0];
					this.k = new double[9];
					this.r = new double[9];
					this.p = new double[12];
					this.binning_x = 0;
					this.binning_y = 0;
					this.roi = new sensor_msgs.msg.RegionOfInterest();
				}

				public CameraInfoForSIGVerseBridge(std_msgs.msg.Header header, System.UInt32 height, System.UInt32 width, string distortion_model, double[]  d, double[]  k, double[]  r, double[]  p, System.UInt32 binning_x, System.UInt32 binning_y, sensor_msgs.msg.RegionOfInterest roi)
				{
					this.header = header;
					this.height = height;
					this.width = width;
					this.distortion_model = distortion_model;
					this.d = d;
					this.k = k;
					this.r = r;
					this.p = p;
					this.binning_x = binning_x;
					this.binning_y = binning_y;
					this.roi = roi;
				}

				new public static string GetMessageType()
				{
					return "sensor_msgs/msg/CameraInfo";
				}

			} // class CameraInfo
		} // namespace msg
	} // namespace sensor_msgs
} // namespace SIGVerse.RosBridge
