// Generated by gencs from sensor_msgs/msg/ChannelFloat32.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace sensor_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class ChannelFloat32 : RosMessage
			{
				public string name;
				public System.Collections.Generic.List<float>  values;


				public ChannelFloat32()
				{
					this.name = "";
					this.values = new System.Collections.Generic.List<float>();
				}

				public ChannelFloat32(string name, System.Collections.Generic.List<float>  values)
				{
					this.name = name;
					this.values = values;
				}

				new public static string GetMessageType()
				{
					return "sensor_msgs/msg/ChannelFloat32";
				}

			} // class ChannelFloat32
		} // namespace msg
	} // namespace sensor_msgs
} // namespace SIGVerse.RosBridge
