// Generated by gencs from sensor_msgs/msg/CompressedImage.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace sensor_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class CompressedImage : RosMessage
			{
				public std_msgs.msg.Header header;
				public string format;
				public System.Collections.Generic.List<byte>  data;


				public CompressedImage()
				{
					this.header = new std_msgs.msg.Header();
					this.format = "";
					this.data = new System.Collections.Generic.List<byte>();
				}

				public CompressedImage(std_msgs.msg.Header header, string format, System.Collections.Generic.List<byte>  data)
				{
					this.header = header;
					this.format = format;
					this.data = data;
				}

				new public static string GetMessageType()
				{
					return "sensor_msgs/msg/CompressedImage";
				}

			} // class CompressedImage
		} // namespace msg
	} // namespace sensor_msgs
} // namespace SIGVerse.RosBridge
