// Generated by gencs from sensor_msgs/msg/FluidPressure.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace sensor_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class FluidPressure : RosMessage
			{
				public std_msgs.msg.Header header;
				public double fluid_pressure;
				public double variance;


				public FluidPressure()
				{
					this.header = new std_msgs.msg.Header();
					this.fluid_pressure = 0.0;
					this.variance = 0.0;
				}

				public FluidPressure(std_msgs.msg.Header header, double fluid_pressure, double variance)
				{
					this.header = header;
					this.fluid_pressure = fluid_pressure;
					this.variance = variance;
				}

				new public static string GetMessageType()
				{
					return "sensor_msgs/msg/FluidPressure";
				}

			} // class FluidPressure
		} // namespace msg
	} // namespace sensor_msgs
} // namespace SIGVerse.RosBridge
