// Generated by gencs from sensor_msgs/msg/Illuminance.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace sensor_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class Illuminance : RosMessage
			{
				public std_msgs.msg.Header header;
				public double illuminance;
				public double variance;


				public Illuminance()
				{
					this.header = new std_msgs.msg.Header();
					this.illuminance = 0.0;
					this.variance = 0.0;
				}

				public Illuminance(std_msgs.msg.Header header, double illuminance, double variance)
				{
					this.header = header;
					this.illuminance = illuminance;
					this.variance = variance;
				}

				new public static string GetMessageType()
				{
					return "sensor_msgs/msg/Illuminance";
				}

			} // class Illuminance
		} // namespace msg
	} // namespace sensor_msgs
} // namespace SIGVerse.RosBridge
