// Generated by gencs from sensor_msgs/msg/Image.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace sensor_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class ImageForSIGVerseBridge : RosMessage
			{
				public std_msgs.msg.Header header;
				public System.UInt32 height;
				public System.UInt32 width;
				public string encoding;
				public byte is_bigendian;
				public System.UInt32 step;
				public byte[] data;


				public ImageForSIGVerseBridge()
				{
					this.header = new std_msgs.msg.Header();
					this.height = 0;
					this.width = 0;
					this.encoding = "";
					this.is_bigendian = 0;
					this.step = 0;
					this.data = null;
				}

				public ImageForSIGVerseBridge(std_msgs.msg.Header header, System.UInt32 height, System.UInt32 width, string encoding, byte is_bigendian, System.UInt32 step, byte[]  data)
				{
					this.header = header;
					this.height = height;
					this.width = width;
					this.encoding = encoding;
					this.is_bigendian = is_bigendian;
					this.step = step;
					this.data = data;
				}

				new public static string GetMessageType()
				{
					return "sensor_msgs/msg/Image";
				}

			} // class Image
		} // namespace msg
	} // namespace sensor_msgs
} // namespace SIGVerse.RosBridge
