// Generated by gencs from sensor_msgs/msg/Joy.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace sensor_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class Joy : RosMessage
			{
				public std_msgs.msg.Header header;
				public System.Collections.Generic.List<float>  axes;
				public System.Collections.Generic.List<System.Int32>  buttons;


				public Joy()
				{
					this.header = new std_msgs.msg.Header();
					this.axes = new System.Collections.Generic.List<float>();
					this.buttons = new System.Collections.Generic.List<System.Int32>();
				}

				public Joy(std_msgs.msg.Header header, System.Collections.Generic.List<float>  axes, System.Collections.Generic.List<System.Int32>  buttons)
				{
					this.header = header;
					this.axes = axes;
					this.buttons = buttons;
				}

				new public static string GetMessageType()
				{
					return "sensor_msgs/msg/Joy";
				}

			} // class Joy
		} // namespace msg
	} // namespace sensor_msgs
} // namespace SIGVerse.RosBridge
