// Generated by gencs from sensor_msgs/msg/JoyFeedback.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace sensor_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class JoyFeedback : RosMessage
			{
				public byte type;
				public byte id;
				public float intensity;

				// Constants:
				public const byte TYPE_LED = 0;
				public const byte TYPE_RUMBLE = 1;
				public const byte TYPE_BUZZER = 2;

				public JoyFeedback()
				{
					this.type = 0;
					this.id = 0;
					this.intensity = 0.0f;
				}

				public JoyFeedback(byte type, byte id, float intensity)
				{
					this.type = type;
					this.id = id;
					this.intensity = intensity;
				}

				new public static string GetMessageType()
				{
					return "sensor_msgs/msg/JoyFeedback";
				}

			} // class JoyFeedback
		} // namespace msg
	} // namespace sensor_msgs
} // namespace SIGVerse.RosBridge
