// Generated by gencs from sensor_msgs/msg/JoyFeedbackArray.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.sensor_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace sensor_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class JoyFeedbackArray : RosMessage
			{
				public System.Collections.Generic.List<sensor_msgs.msg.JoyFeedback>  array;


				public JoyFeedbackArray()
				{
					this.array = new System.Collections.Generic.List<sensor_msgs.msg.JoyFeedback>();
				}

				public JoyFeedbackArray(System.Collections.Generic.List<sensor_msgs.msg.JoyFeedback>  array)
				{
					this.array = array;
				}

				new public static string GetMessageType()
				{
					return "sensor_msgs/msg/JoyFeedbackArray";
				}

			} // class JoyFeedbackArray
		} // namespace msg
	} // namespace sensor_msgs
} // namespace SIGVerse.RosBridge
