// Generated by gencs from sensor_msgs/msg/LaserScan.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace sensor_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class LaserScanForSIGVerseBridge : RosMessage
			{
				public std_msgs.msg.Header header;
				public double angle_min; // Changed to double because the BSON parser doesn't support float
				public double angle_max;
				public double angle_increment;
				public double time_increment;
				public double scan_time;
				public double range_min;
				public double range_max;
				public double[]  ranges;
				public double[]  intensities;


				public LaserScanForSIGVerseBridge()
				{
					this.header = new std_msgs.msg.Header();
					this.angle_min = 0.0;
					this.angle_max = 0.0;
					this.angle_increment = 0.0;
					this.time_increment = 0.0;
					this.scan_time = 0.0;
					this.range_min = 0.0;
					this.range_max = 0.0;
					this.ranges = null;
					this.intensities = null;
				}

				public LaserScanForSIGVerseBridge(std_msgs.msg.Header header, double angle_min, double angle_max, double angle_increment, double time_increment, double scan_time, double range_min, double range_max, double[] ranges, double[] intensities)
				{
					this.header = header;
					this.angle_min = angle_min;
					this.angle_max = angle_max;
					this.angle_increment = angle_increment;
					this.time_increment = time_increment;
					this.scan_time = scan_time;
					this.range_min = range_min;
					this.range_max = range_max;
					this.ranges = ranges;
					this.intensities = intensities;
				}

				new public static string GetMessageType()
				{
					return "sensor_msgs/msg/LaserScan";
				}

			} // class LaserScan
		} // namespace msg
	} // namespace sensor_msgs
} // namespace SIGVerse.RosBridge
