// Generated by gencs from sensor_msgs/msg/LaserEcho.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace sensor_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class LaserEcho : RosMessage
			{
				public System.Collections.Generic.List<float>  echoes;


				public LaserEcho()
				{
					this.echoes = new System.Collections.Generic.List<float>();
				}

				public LaserEcho(System.Collections.Generic.List<float>  echoes)
				{
					this.echoes = echoes;
				}

				new public static string GetMessageType()
				{
					return "sensor_msgs/msg/LaserEcho";
				}

			} // class LaserEcho
		} // namespace msg
	} // namespace sensor_msgs
} // namespace SIGVerse.RosBridge
