// Generated by gencs from sensor_msgs/msg/MagneticField.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs.msg;
using SIGVerse.RosBridge.geometry_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace sensor_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class MagneticField : RosMessage
			{
				public std_msgs.msg.Header header;
				public UnityEngine.Vector3 magnetic_field;
				public double[]  magnetic_field_covariance;


				public MagneticField()
				{
					this.header = new std_msgs.msg.Header();
					this.magnetic_field = new UnityEngine.Vector3();
					this.magnetic_field_covariance = new double[9];
				}

				public MagneticField(std_msgs.msg.Header header, UnityEngine.Vector3 magnetic_field, double[]  magnetic_field_covariance)
				{
					this.header = header;
					this.magnetic_field = magnetic_field;
					this.magnetic_field_covariance = magnetic_field_covariance;
				}

				new public static string GetMessageType()
				{
					return "sensor_msgs/msg/MagneticField";
				}

			} // class MagneticField
		} // namespace msg
	} // namespace sensor_msgs
} // namespace SIGVerse.RosBridge
