// Generated by gencs from sensor_msgs/msg/MultiDOFJointState.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs.msg;
using SIGVerse.RosBridge.geometry_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace sensor_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class MultiDOFJointState : RosMessage
			{
				public std_msgs.msg.Header header;
				public System.Collections.Generic.List<string>  joint_names;
				public System.Collections.Generic.List<geometry_msgs.msg.Transform>  transforms;
				public System.Collections.Generic.List<geometry_msgs.msg.Twist>  twist;
				public System.Collections.Generic.List<geometry_msgs.msg.Wrench>  wrench;


				public MultiDOFJointState()
				{
					this.header = new std_msgs.msg.Header();
					this.joint_names = new System.Collections.Generic.List<string>();
					this.transforms = new System.Collections.Generic.List<geometry_msgs.msg.Transform>();
					this.twist = new System.Collections.Generic.List<geometry_msgs.msg.Twist>();
					this.wrench = new System.Collections.Generic.List<geometry_msgs.msg.Wrench>();
				}

				public MultiDOFJointState(std_msgs.msg.Header header, System.Collections.Generic.List<string>  joint_names, System.Collections.Generic.List<geometry_msgs.msg.Transform>  transforms, System.Collections.Generic.List<geometry_msgs.msg.Twist>  twist, System.Collections.Generic.List<geometry_msgs.msg.Wrench>  wrench)
				{
					this.header = header;
					this.joint_names = joint_names;
					this.transforms = transforms;
					this.twist = twist;
					this.wrench = wrench;
				}

				new public static string GetMessageType()
				{
					return "sensor_msgs/msg/MultiDOFJointState";
				}

			} // class MultiDOFJointState
		} // namespace msg
	} // namespace sensor_msgs
} // namespace SIGVerse.RosBridge
