// Generated by gencs from sensor_msgs/msg/PointCloud2.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs.msg;
using SIGVerse.RosBridge.sensor_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace sensor_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class PointCloud2 : RosMessage
			{
				public std_msgs.msg.Header header;
				public System.UInt32 height;
				public System.UInt32 width;
				public System.Collections.Generic.List<sensor_msgs.msg.PointField>  fields;
				public bool is_bigendian;
				public System.UInt32 point_step;
				public System.UInt32 row_step;
				public System.Collections.Generic.List<byte>  data;
				public bool is_dense;


				public PointCloud2()
				{
					this.header = new std_msgs.msg.Header();
					this.height = 0;
					this.width = 0;
					this.fields = new System.Collections.Generic.List<sensor_msgs.msg.PointField>();
					this.is_bigendian = false;
					this.point_step = 0;
					this.row_step = 0;
					this.data = new System.Collections.Generic.List<byte>();
					this.is_dense = false;
				}

				public PointCloud2(std_msgs.msg.Header header, System.UInt32 height, System.UInt32 width, System.Collections.Generic.List<sensor_msgs.msg.PointField>  fields, bool is_bigendian, System.UInt32 point_step, System.UInt32 row_step, System.Collections.Generic.List<byte>  data, bool is_dense)
				{
					this.header = header;
					this.height = height;
					this.width = width;
					this.fields = fields;
					this.is_bigendian = is_bigendian;
					this.point_step = point_step;
					this.row_step = row_step;
					this.data = data;
					this.is_dense = is_dense;
				}

				new public static string GetMessageType()
				{
					return "sensor_msgs/msg/PointCloud2";
				}

			} // class PointCloud2
		} // namespace msg
	} // namespace sensor_msgs
} // namespace SIGVerse.RosBridge
