// Generated by gencs from sensor_msgs/msg/PointField.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace sensor_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class PointField : RosMessage
			{
				public string name;
				public System.UInt32 offset;
				public byte datatype;
				public System.UInt32 count;

				// Constants:
				public const byte INT8 = 1;
				public const byte UINT8 = 2;
				public const byte INT16 = 3;
				public const byte UINT16 = 4;
				public const byte INT32 = 5;
				public const byte UINT32 = 6;
				public const byte FLOAT32 = 7;
				public const byte FLOAT64 = 8;

				public PointField()
				{
					this.name = "";
					this.offset = 0;
					this.datatype = 0;
					this.count = 0;
				}

				public PointField(string name, System.UInt32 offset, byte datatype, System.UInt32 count)
				{
					this.name = name;
					this.offset = offset;
					this.datatype = datatype;
					this.count = count;
				}

				new public static string GetMessageType()
				{
					return "sensor_msgs/msg/PointField";
				}

			} // class PointField
		} // namespace msg
	} // namespace sensor_msgs
} // namespace SIGVerse.RosBridge
