// Generated by gencs from sensor_msgs/msg/PointCloud.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs.msg;
using SIGVerse.RosBridge.geometry_msgs.msg;
using SIGVerse.RosBridge.sensor_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace sensor_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class PointCloud : RosMessage
			{
				public std_msgs.msg.Header header;
				public System.Collections.Generic.List<geometry_msgs.msg.Point32>  points;
				public System.Collections.Generic.List<sensor_msgs.msg.ChannelFloat32>  channels;


				public PointCloud()
				{
					this.header = new std_msgs.msg.Header();
					this.points = new System.Collections.Generic.List<geometry_msgs.msg.Point32>();
					this.channels = new System.Collections.Generic.List<sensor_msgs.msg.ChannelFloat32>();
				}

				public PointCloud(std_msgs.msg.Header header, System.Collections.Generic.List<geometry_msgs.msg.Point32>  points, System.Collections.Generic.List<sensor_msgs.msg.ChannelFloat32>  channels)
				{
					this.header = header;
					this.points = points;
					this.channels = channels;
				}

				new public static string GetMessageType()
				{
					return "sensor_msgs/msg/PointCloud";
				}

			} // class PointCloud
		} // namespace msg
	} // namespace sensor_msgs
} // namespace SIGVerse.RosBridge
