// Generated by gencs from sensor_msgs/msg/RelativeHumidity.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace sensor_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class RelativeHumidity : RosMessage
			{
				public std_msgs.msg.Header header;
				public double relative_humidity;
				public double variance;


				public RelativeHumidity()
				{
					this.header = new std_msgs.msg.Header();
					this.relative_humidity = 0.0;
					this.variance = 0.0;
				}

				public RelativeHumidity(std_msgs.msg.Header header, double relative_humidity, double variance)
				{
					this.header = header;
					this.relative_humidity = relative_humidity;
					this.variance = variance;
				}

				new public static string GetMessageType()
				{
					return "sensor_msgs/msg/RelativeHumidity";
				}

			} // class RelativeHumidity
		} // namespace msg
	} // namespace sensor_msgs
} // namespace SIGVerse.RosBridge
