// Generated by gencs from sensor_msgs/msg/Temperature.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace sensor_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class Temperature : RosMessage
			{
				public std_msgs.msg.Header header;
				public double temperature;
				public double variance;


				public Temperature()
				{
					this.header = new std_msgs.msg.Header();
					this.temperature = 0.0;
					this.variance = 0.0;
				}

				public Temperature(std_msgs.msg.Header header, double temperature, double variance)
				{
					this.header = header;
					this.temperature = temperature;
					this.variance = variance;
				}

				new public static string GetMessageType()
				{
					return "sensor_msgs/msg/Temperature";
				}

			} // class Temperature
		} // namespace msg
	} // namespace sensor_msgs
} // namespace SIGVerse.RosBridge
