// Generated by gencs from sensor_msgs/msg/TimeReference.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs.msg;
using SIGVerse.RosBridge.builtin_interfaces.msg;

namespace SIGVerse.RosBridge 
{
	namespace sensor_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class TimeReference : RosMessage
			{
				public std_msgs.msg.Header header;
				public builtin_interfaces.msg.Time time_ref;
				public string source;


				public TimeReference()
				{
					this.header = new std_msgs.msg.Header();
					this.time_ref = new builtin_interfaces.msg.Time();
					this.source = "";
				}

				public TimeReference(std_msgs.msg.Header header, builtin_interfaces.msg.Time time_ref, string source)
				{
					this.header = header;
					this.time_ref = time_ref;
					this.source = source;
				}

				new public static string GetMessageType()
				{
					return "sensor_msgs/msg/TimeReference";
				}

			} // class TimeReference
		} // namespace msg
	} // namespace sensor_msgs
} // namespace SIGVerse.RosBridge
