// Generated by gencs from std_msgs/msg/Bool.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace std_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class Bool : RosMessage
			{
				public bool data;


				public Bool()
				{
					this.data = false;
				}

				public Bool(bool data)
				{
					this.data = data;
				}

				new public static string GetMessageType()
				{
					return "std_msgs/msg/Bool";
				}

			} // class Bool
		} // namespace msg
	} // namespace std_msgs
} // namespace SIGVerse.RosBridge
