// Generated by gencs from std_msgs/msg/Byte.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace std_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class Byte : RosMessage
			{
				public sbyte data;


				public Byte()
				{
					this.data = 0;
				}

				public Byte(sbyte data)
				{
					this.data = data;
				}

				new public static string GetMessageType()
				{
					return "std_msgs/msg/Byte";
				}

			} // class Byte
		} // namespace msg
	} // namespace std_msgs
} // namespace SIGVerse.RosBridge
