// Generated by gencs from std_msgs/msg/Char.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace std_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class Char : RosMessage
			{
				public byte data;


				public Char()
				{
					this.data = 0;
				}

				public Char(byte data)
				{
					this.data = data;
				}

				new public static string GetMessageType()
				{
					return "std_msgs/msg/Char";
				}

			} // class Char
		} // namespace msg
	} // namespace std_msgs
} // namespace SIGVerse.RosBridge
