// Generated by gencs from std_msgs/msg/ColorRGBA.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace std_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class ColorRGBA : RosMessage
			{
				public float r;
				public float g;
				public float b;
				public float a;


				public ColorRGBA()
				{
					this.r = 0.0f;
					this.g = 0.0f;
					this.b = 0.0f;
					this.a = 0.0f;
				}

				public ColorRGBA(float r, float g, float b, float a)
				{
					this.r = r;
					this.g = g;
					this.b = b;
					this.a = a;
				}

				new public static string GetMessageType()
				{
					return "std_msgs/msg/ColorRGBA";
				}

			} // class ColorRGBA
		} // namespace msg
	} // namespace std_msgs
} // namespace SIGVerse.RosBridge
