// Generated by gencs from std_msgs/msg/Empty.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace std_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class Empty : RosMessage
			{
				public byte structure_needs_at_least_one_member;


				public Empty()
				{
					this.structure_needs_at_least_one_member = 0;
				}

				public Empty(byte structure_needs_at_least_one_member)
				{
					this.structure_needs_at_least_one_member = structure_needs_at_least_one_member;
				}

				new public static string GetMessageType()
				{
					return "std_msgs/msg/Empty";
				}

			} // class Empty
		} // namespace msg
	} // namespace std_msgs
} // namespace SIGVerse.RosBridge
