// Generated by gencs from std_msgs/msg/Float32.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace std_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class Float32 : RosMessage
			{
				public float data;


				public Float32()
				{
					this.data = 0.0f;
				}

				public Float32(float data)
				{
					this.data = data;
				}

				new public static string GetMessageType()
				{
					return "std_msgs/msg/Float32";
				}

			} // class Float32
		} // namespace msg
	} // namespace std_msgs
} // namespace SIGVerse.RosBridge
