// Generated by gencs from std_msgs/msg/Float64.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace std_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class Float64 : RosMessage
			{
				public double data;


				public Float64()
				{
					this.data = 0.0;
				}

				public Float64(double data)
				{
					this.data = data;
				}

				new public static string GetMessageType()
				{
					return "std_msgs/msg/Float64";
				}

			} // class Float64
		} // namespace msg
	} // namespace std_msgs
} // namespace SIGVerse.RosBridge
