// Generated by gencs from std_msgs/msg/Header.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.builtin_interfaces.msg;

namespace SIGVerse.RosBridge 
{
	namespace std_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class Header : RosMessage
			{
				// Added by hand
				private static readonly DateTime UnixEpoch = new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc);

				private static TimeSpan timeGap = TimeSpan.Zero;
				private static object lockTimeGap = new object();

				public builtin_interfaces.msg.Time stamp;
				public string frame_id;


				public Header()
				{
					this.stamp = new builtin_interfaces.msg.Time();
					this.frame_id = "";
				}

				public Header(builtin_interfaces.msg.Time stamp, string frame_id)
				{
					this.stamp = stamp;
					this.frame_id = frame_id;
				}

				new public static string GetMessageType()
				{
					return "std_msgs/msg/Header";
				}

				// Added by hand
				public void Update()
				{
					if(SIGVerse.Common.ConfigManager.Instance.configInfo.setUpRosTimestamp)
					{
						TimeSpan epochTime = (DateTime.Now.ToUniversalTime() - UnixEpoch);

						lock (lockTimeGap)
						{
							epochTime = epochTime.Subtract(timeGap);
						}

						this.stamp.sec     = (int) epochTime.TotalSeconds;
						this.stamp.nanosec = (uint)epochTime.Milliseconds * 1000 * 1000;
					}
				}

				// Added by hand
				public static void SetTimeGap(int secs, int millisecs)
				{
					lock (lockTimeGap)
					{
						timeGap = new TimeSpan(0, 0, 0, secs, millisecs);
					}
				}

			} // class Header
		} // namespace msg
	} // namespace std_msgs
} // namespace SIGVerse.RosBridge
