// Generated by gencs from std_msgs/msg/Int16.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace std_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class Int16 : RosMessage
			{
				public System.Int16 data;


				public Int16()
				{
					this.data = 0;
				}

				public Int16(System.Int16 data)
				{
					this.data = data;
				}

				new public static string GetMessageType()
				{
					return "std_msgs/msg/Int16";
				}

			} // class Int16
		} // namespace msg
	} // namespace std_msgs
} // namespace SIGVerse.RosBridge
