// Generated by gencs from std_msgs/msg/Int32.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace std_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class Int32 : RosMessage
			{
				public System.Int32 data;


				public Int32()
				{
					this.data = 0;
				}

				public Int32(System.Int32 data)
				{
					this.data = data;
				}

				new public static string GetMessageType()
				{
					return "std_msgs/msg/Int32";
				}

			} // class Int32
		} // namespace msg
	} // namespace std_msgs
} // namespace SIGVerse.RosBridge
