// Generated by gencs from std_msgs/msg/Int64.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace std_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class Int64 : RosMessage
			{
				public System.Int64 data;


				public Int64()
				{
					this.data = 0;
				}

				public Int64(System.Int64 data)
				{
					this.data = data;
				}

				new public static string GetMessageType()
				{
					return "std_msgs/msg/Int64";
				}

			} // class Int64
		} // namespace msg
	} // namespace std_msgs
} // namespace SIGVerse.RosBridge
