// Generated by gencs from std_msgs/msg/Int8MultiArray.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace std_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class Int8MultiArray : RosMessage
			{
				public std_msgs.msg.MultiArrayLayout layout;
				public System.Collections.Generic.List<sbyte>  data;


				public Int8MultiArray()
				{
					this.layout = new std_msgs.msg.MultiArrayLayout();
					this.data = new System.Collections.Generic.List<sbyte>();
				}

				public Int8MultiArray(std_msgs.msg.MultiArrayLayout layout, System.Collections.Generic.List<sbyte>  data)
				{
					this.layout = layout;
					this.data = data;
				}

				new public static string GetMessageType()
				{
					return "std_msgs/msg/Int8MultiArray";
				}

			} // class Int8MultiArray
		} // namespace msg
	} // namespace std_msgs
} // namespace SIGVerse.RosBridge
