// Generated by gencs from std_msgs/msg/Int8.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace std_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class Int8 : RosMessage
			{
				public sbyte data;


				public Int8()
				{
					this.data = 0;
				}

				public Int8(sbyte data)
				{
					this.data = data;
				}

				new public static string GetMessageType()
				{
					return "std_msgs/msg/Int8";
				}

			} // class Int8
		} // namespace msg
	} // namespace std_msgs
} // namespace SIGVerse.RosBridge
