// Generated by gencs from std_msgs/msg/MultiArrayLayout.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace std_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class MultiArrayLayout : RosMessage
			{
				public System.Collections.Generic.List<std_msgs.msg.MultiArrayDimension>  dim;
				public System.UInt32 data_offset;


				public MultiArrayLayout()
				{
					this.dim = new System.Collections.Generic.List<std_msgs.msg.MultiArrayDimension>();
					this.data_offset = 0;
				}

				public MultiArrayLayout(System.Collections.Generic.List<std_msgs.msg.MultiArrayDimension>  dim, System.UInt32 data_offset)
				{
					this.dim = dim;
					this.data_offset = data_offset;
				}

				new public static string GetMessageType()
				{
					return "std_msgs/msg/MultiArrayLayout";
				}

			} // class MultiArrayLayout
		} // namespace msg
	} // namespace std_msgs
} // namespace SIGVerse.RosBridge
