// Generated by gencs from std_msgs/msg/MultiArrayDimension.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace std_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class MultiArrayDimension : RosMessage
			{
				public string label;
				public System.UInt32 size;
				public System.UInt32 stride;


				public MultiArrayDimension()
				{
					this.label = "";
					this.size = 0;
					this.stride = 0;
				}

				public MultiArrayDimension(string label, System.UInt32 size, System.UInt32 stride)
				{
					this.label = label;
					this.size = size;
					this.stride = stride;
				}

				new public static string GetMessageType()
				{
					return "std_msgs/msg/MultiArrayDimension";
				}

			} // class MultiArrayDimension
		} // namespace msg
	} // namespace std_msgs
} // namespace SIGVerse.RosBridge
