// Generated by gencs from std_msgs/msg/String.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace std_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class String : RosMessage
			{
				public string data;


				public String()
				{
					this.data = "";
				}

				public String(string data)
				{
					this.data = data;
				}

				new public static string GetMessageType()
				{
					return "std_msgs/msg/String";
				}

			} // class String
		} // namespace msg
	} // namespace std_msgs
} // namespace SIGVerse.RosBridge
