// Generated by gencs from std_msgs/msg/UInt16MultiArray.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace std_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class UInt16MultiArray : RosMessage
			{
				public std_msgs.msg.MultiArrayLayout layout;
				public System.Collections.Generic.List<System.UInt16>  data;


				public UInt16MultiArray()
				{
					this.layout = new std_msgs.msg.MultiArrayLayout();
					this.data = new System.Collections.Generic.List<System.UInt16>();
				}

				public UInt16MultiArray(std_msgs.msg.MultiArrayLayout layout, System.Collections.Generic.List<System.UInt16>  data)
				{
					this.layout = layout;
					this.data = data;
				}

				new public static string GetMessageType()
				{
					return "std_msgs/msg/UInt16MultiArray";
				}

			} // class UInt16MultiArray
		} // namespace msg
	} // namespace std_msgs
} // namespace SIGVerse.RosBridge
