// Generated by gencs from std_msgs/msg/UInt32.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace std_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class UInt32 : RosMessage
			{
				public System.UInt32 data;


				public UInt32()
				{
					this.data = 0;
				}

				public UInt32(System.UInt32 data)
				{
					this.data = data;
				}

				new public static string GetMessageType()
				{
					return "std_msgs/msg/UInt32";
				}

			} // class UInt32
		} // namespace msg
	} // namespace std_msgs
} // namespace SIGVerse.RosBridge
