// Generated by gencs from std_msgs/msg/UInt16.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace std_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class UInt16 : RosMessage
			{
				public System.UInt16 data;


				public UInt16()
				{
					this.data = 0;
				}

				public UInt16(System.UInt16 data)
				{
					this.data = data;
				}

				new public static string GetMessageType()
				{
					return "std_msgs/msg/UInt16";
				}

			} // class UInt16
		} // namespace msg
	} // namespace std_msgs
} // namespace SIGVerse.RosBridge
