// Generated by gencs from geometry_msgs/msg/Accel.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.geometry_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace geometry_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class Accel : RosMessage
			{
				public UnityEngine.Vector3 linear;
				public UnityEngine.Vector3 angular;


				public Accel()
				{
					this.linear = new UnityEngine.Vector3();
					this.angular = new UnityEngine.Vector3();
				}

				public Accel(UnityEngine.Vector3 linear, UnityEngine.Vector3 angular)
				{
					this.linear = linear;
					this.angular = angular;
				}

				new public static string GetMessageType()
				{
					return "geometry_msgs/msg/Accel";
				}

			} // class Accel
		} // namespace msg
	} // namespace geometry_msgs
} // namespace SIGVerse.RosBridge
