// Generated by gencs from geometry_msgs/msg/AccelStamped.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs.msg;
using SIGVerse.RosBridge.geometry_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace geometry_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class AccelStamped : RosMessage
			{
				public std_msgs.msg.Header header;
				public geometry_msgs.msg.Accel accel;


				public AccelStamped()
				{
					this.header = new std_msgs.msg.Header();
					this.accel = new geometry_msgs.msg.Accel();
				}

				public AccelStamped(std_msgs.msg.Header header, geometry_msgs.msg.Accel accel)
				{
					this.header = header;
					this.accel = accel;
				}

				new public static string GetMessageType()
				{
					return "geometry_msgs/msg/AccelStamped";
				}

			} // class AccelStamped
		} // namespace msg
	} // namespace geometry_msgs
} // namespace SIGVerse.RosBridge
