// Generated by gencs from geometry_msgs/msg/AccelWithCovariance.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.geometry_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace geometry_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class AccelWithCovariance : RosMessage
			{
				public geometry_msgs.msg.Accel accel;
				public double[]  covariance;


				public AccelWithCovariance()
				{
					this.accel = new geometry_msgs.msg.Accel();
					this.covariance = new double[36];
				}

				public AccelWithCovariance(geometry_msgs.msg.Accel accel, double[]  covariance)
				{
					this.accel = accel;
					this.covariance = covariance;
				}

				new public static string GetMessageType()
				{
					return "geometry_msgs/msg/AccelWithCovariance";
				}

			} // class AccelWithCovariance
		} // namespace msg
	} // namespace geometry_msgs
} // namespace SIGVerse.RosBridge
