// Generated by gencs from geometry_msgs/msg/InertiaStamped.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs.msg;
using SIGVerse.RosBridge.geometry_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace geometry_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class InertiaStamped : RosMessage
			{
				public std_msgs.msg.Header header;
				public geometry_msgs.msg.Inertia inertia;


				public InertiaStamped()
				{
					this.header = new std_msgs.msg.Header();
					this.inertia = new geometry_msgs.msg.Inertia();
				}

				public InertiaStamped(std_msgs.msg.Header header, geometry_msgs.msg.Inertia inertia)
				{
					this.header = header;
					this.inertia = inertia;
				}

				new public static string GetMessageType()
				{
					return "geometry_msgs/msg/InertiaStamped";
				}

			} // class InertiaStamped
		} // namespace msg
	} // namespace geometry_msgs
} // namespace SIGVerse.RosBridge
