// Generated by gencs from geometry_msgs/msg/Inertia.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.geometry_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace geometry_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class Inertia : RosMessage
			{
				public double m;
				public UnityEngine.Vector3 com;
				public double ixx;
				public double ixy;
				public double ixz;
				public double iyy;
				public double iyz;
				public double izz;


				public Inertia()
				{
					this.m = 0.0;
					this.com = new UnityEngine.Vector3();
					this.ixx = 0.0;
					this.ixy = 0.0;
					this.ixz = 0.0;
					this.iyy = 0.0;
					this.iyz = 0.0;
					this.izz = 0.0;
				}

				public Inertia(double m, UnityEngine.Vector3 com, double ixx, double ixy, double ixz, double iyy, double iyz, double izz)
				{
					this.m = m;
					this.com = com;
					this.ixx = ixx;
					this.ixy = ixy;
					this.ixz = ixz;
					this.iyy = iyy;
					this.iyz = iyz;
					this.izz = izz;
				}

				new public static string GetMessageType()
				{
					return "geometry_msgs/msg/Inertia";
				}

			} // class Inertia
		} // namespace msg
	} // namespace geometry_msgs
} // namespace SIGVerse.RosBridge
