// Generated by gencs from geometry_msgs/msg/Point32.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace geometry_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class Point32 : RosMessage
			{
				public float x;
				public float y;
				public float z;


				public Point32()
				{
					this.x = 0.0f;
					this.y = 0.0f;
					this.z = 0.0f;
				}

				public Point32(float x, float y, float z)
				{
					this.x = x;
					this.y = y;
					this.z = z;
				}

				new public static string GetMessageType()
				{
					return "geometry_msgs/msg/Point32";
				}

			} // class Point32
		} // namespace msg
	} // namespace geometry_msgs
} // namespace SIGVerse.RosBridge
