// Generated by gencs from geometry_msgs/msg/Point.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace geometry_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class Point : RosMessage
			{
				public double x;
				public double y;
				public double z;


				public Point()
				{
					this.x = 0.0;
					this.y = 0.0;
					this.z = 0.0;
				}

				public Point(double x, double y, double z)
				{
					this.x = x;
					this.y = y;
					this.z = z;
				}

				new public static string GetMessageType()
				{
					return "geometry_msgs/msg/Point";
				}

			} // class Point
		} // namespace msg
	} // namespace geometry_msgs
} // namespace SIGVerse.RosBridge
