// Generated by gencs from geometry_msgs/msg/PointStamped.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs.msg;
using SIGVerse.RosBridge.geometry_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace geometry_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class PointStamped : RosMessage
			{
				public std_msgs.msg.Header header;
				public UnityEngine.Vector3 point;


				public PointStamped()
				{
					this.header = new std_msgs.msg.Header();
					this.point = new UnityEngine.Vector3();
				}

				public PointStamped(std_msgs.msg.Header header, UnityEngine.Vector3 point)
				{
					this.header = header;
					this.point = point;
				}

				new public static string GetMessageType()
				{
					return "geometry_msgs/msg/PointStamped";
				}

			} // class PointStamped
		} // namespace msg
	} // namespace geometry_msgs
} // namespace SIGVerse.RosBridge
