// Generated by gencs from geometry_msgs/msg/PolygonStamped.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs.msg;
using SIGVerse.RosBridge.geometry_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace geometry_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class PolygonStamped : RosMessage
			{
				public std_msgs.msg.Header header;
				public geometry_msgs.msg.Polygon polygon;


				public PolygonStamped()
				{
					this.header = new std_msgs.msg.Header();
					this.polygon = new geometry_msgs.msg.Polygon();
				}

				public PolygonStamped(std_msgs.msg.Header header, geometry_msgs.msg.Polygon polygon)
				{
					this.header = header;
					this.polygon = polygon;
				}

				new public static string GetMessageType()
				{
					return "geometry_msgs/msg/PolygonStamped";
				}

			} // class PolygonStamped
		} // namespace msg
	} // namespace geometry_msgs
} // namespace SIGVerse.RosBridge
