// Generated by gencs from geometry_msgs/msg/PolygonInstance.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.geometry_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace geometry_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class PolygonInstance : RosMessage
			{
				public geometry_msgs.msg.Polygon polygon;
				public System.Int64 id;


				public PolygonInstance()
				{
					this.polygon = new geometry_msgs.msg.Polygon();
					this.id = 0;
				}

				public PolygonInstance(geometry_msgs.msg.Polygon polygon, System.Int64 id)
				{
					this.polygon = polygon;
					this.id = id;
				}

				new public static string GetMessageType()
				{
					return "geometry_msgs/msg/PolygonInstance";
				}

			} // class PolygonInstance
		} // namespace msg
	} // namespace geometry_msgs
} // namespace SIGVerse.RosBridge
