// Generated by gencs from geometry_msgs/msg/Polygon.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.geometry_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace geometry_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class Polygon : RosMessage
			{
				public System.Collections.Generic.List<geometry_msgs.msg.Point32>  points;


				public Polygon()
				{
					this.points = new System.Collections.Generic.List<geometry_msgs.msg.Point32>();
				}

				public Polygon(System.Collections.Generic.List<geometry_msgs.msg.Point32>  points)
				{
					this.points = points;
				}

				new public static string GetMessageType()
				{
					return "geometry_msgs/msg/Polygon";
				}

			} // class Polygon
		} // namespace msg
	} // namespace geometry_msgs
} // namespace SIGVerse.RosBridge
