// Generated by gencs from geometry_msgs/msg/PoseArray.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs.msg;
using SIGVerse.RosBridge.geometry_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace geometry_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class PoseArray : RosMessage
			{
				public std_msgs.msg.Header header;
				public System.Collections.Generic.List<geometry_msgs.msg.Pose>  poses;


				public PoseArray()
				{
					this.header = new std_msgs.msg.Header();
					this.poses = new System.Collections.Generic.List<geometry_msgs.msg.Pose>();
				}

				public PoseArray(std_msgs.msg.Header header, System.Collections.Generic.List<geometry_msgs.msg.Pose>  poses)
				{
					this.header = header;
					this.poses = poses;
				}

				new public static string GetMessageType()
				{
					return "geometry_msgs/msg/PoseArray";
				}

			} // class PoseArray
		} // namespace msg
	} // namespace geometry_msgs
} // namespace SIGVerse.RosBridge
