// Generated by gencs from geometry_msgs/msg/PoseWithCovarianceStamped.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs.msg;
using SIGVerse.RosBridge.geometry_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace geometry_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class PoseWithCovarianceStamped : RosMessage
			{
				public std_msgs.msg.Header header;
				public geometry_msgs.msg.PoseWithCovariance pose;


				public PoseWithCovarianceStamped()
				{
					this.header = new std_msgs.msg.Header();
					this.pose = new geometry_msgs.msg.PoseWithCovariance();
				}

				public PoseWithCovarianceStamped(std_msgs.msg.Header header, geometry_msgs.msg.PoseWithCovariance pose)
				{
					this.header = header;
					this.pose = pose;
				}

				new public static string GetMessageType()
				{
					return "geometry_msgs/msg/PoseWithCovarianceStamped";
				}

			} // class PoseWithCovarianceStamped
		} // namespace msg
	} // namespace geometry_msgs
} // namespace SIGVerse.RosBridge
