// Generated by gencs from geometry_msgs/msg/PoseStamped.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs.msg;
using SIGVerse.RosBridge.geometry_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace geometry_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class PoseStamped : RosMessage
			{
				public std_msgs.msg.Header header;
				public geometry_msgs.msg.Pose pose;


				public PoseStamped()
				{
					this.header = new std_msgs.msg.Header();
					this.pose = new geometry_msgs.msg.Pose();
				}

				public PoseStamped(std_msgs.msg.Header header, geometry_msgs.msg.Pose pose)
				{
					this.header = header;
					this.pose = pose;
				}

				new public static string GetMessageType()
				{
					return "geometry_msgs/msg/PoseStamped";
				}

			} // class PoseStamped
		} // namespace msg
	} // namespace geometry_msgs
} // namespace SIGVerse.RosBridge
