// Generated by gencs from geometry_msgs/msg/Pose.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.geometry_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace geometry_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class Pose : RosMessage
			{
				public UnityEngine.Vector3 position;
				public UnityEngine.Quaternion orientation;


				public Pose()
				{
					this.position = new UnityEngine.Vector3();
					this.orientation = new UnityEngine.Quaternion();
				}

				public Pose(UnityEngine.Vector3 position, UnityEngine.Quaternion orientation)
				{
					this.position = position;
					this.orientation = orientation;
				}

				new public static string GetMessageType()
				{
					return "geometry_msgs/msg/Pose";
				}

			} // class Pose
		} // namespace msg
	} // namespace geometry_msgs
} // namespace SIGVerse.RosBridge
