// Generated by gencs from geometry_msgs/msg/PoseWithCovariance.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.geometry_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace geometry_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class PoseWithCovariance : RosMessage
			{
				public geometry_msgs.msg.Pose pose;
				public double[]  covariance;


				public PoseWithCovariance()
				{
					this.pose = new geometry_msgs.msg.Pose();
					this.covariance = new double[36];
				}

				public PoseWithCovariance(geometry_msgs.msg.Pose pose, double[]  covariance)
				{
					this.pose = pose;
					this.covariance = covariance;
				}

				new public static string GetMessageType()
				{
					return "geometry_msgs/msg/PoseWithCovariance";
				}

			} // class PoseWithCovariance
		} // namespace msg
	} // namespace geometry_msgs
} // namespace SIGVerse.RosBridge
