// Generated by gencs from geometry_msgs/msg/Quaternion.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace geometry_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class Quaternion : RosMessage
			{
				public double x;
				public double y;
				public double z;
				public double w;


				public Quaternion()
				{
					this.x = 0.0;
					this.y = 0.0;
					this.z = 0.0;
					this.w = 1.0; // Edited
				}

				public Quaternion(double x, double y, double z, double w)
				{
					this.x = x;
					this.y = y;
					this.z = z;
					this.w = w;
				}

				new public static string GetMessageType()
				{
					return "geometry_msgs/msg/Quaternion";
				}

			} // class Quaternion
		} // namespace msg
	} // namespace geometry_msgs
} // namespace SIGVerse.RosBridge
