// Generated by gencs from geometry_msgs/msg/QuaternionStamped.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs.msg;
using SIGVerse.RosBridge.geometry_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace geometry_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class QuaternionStamped : RosMessage
			{
				public std_msgs.msg.Header header;
				public UnityEngine.Quaternion quaternion;


				public QuaternionStamped()
				{
					this.header = new std_msgs.msg.Header();
					this.quaternion = new UnityEngine.Quaternion();
				}

				public QuaternionStamped(std_msgs.msg.Header header, UnityEngine.Quaternion quaternion)
				{
					this.header = header;
					this.quaternion = quaternion;
				}

				new public static string GetMessageType()
				{
					return "geometry_msgs/msg/QuaternionStamped";
				}

			} // class QuaternionStamped
		} // namespace msg
	} // namespace geometry_msgs
} // namespace SIGVerse.RosBridge
