// Generated by gencs from geometry_msgs/msg/TransformStamped.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs.msg;
using SIGVerse.RosBridge.geometry_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace geometry_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class TransformStamped : RosMessage
			{
				public std_msgs.msg.Header header;
				public string child_frame_id;
				public geometry_msgs.msg.Transform transform;


				public TransformStamped()
				{
					this.header = new std_msgs.msg.Header();
					this.child_frame_id = "";
					this.transform = new geometry_msgs.msg.Transform();
				}

				public TransformStamped(std_msgs.msg.Header header, string child_frame_id, geometry_msgs.msg.Transform transform)
				{
					this.header = header;
					this.child_frame_id = child_frame_id;
					this.transform = transform;
				}

				new public static string GetMessageType()
				{
					return "geometry_msgs/msg/TransformStamped";
				}

			} // class TransformStamped
		} // namespace msg
	} // namespace geometry_msgs
} // namespace SIGVerse.RosBridge
