// Generated by gencs from geometry_msgs/msg/TwistStamped.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs.msg;
using SIGVerse.RosBridge.geometry_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace geometry_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class TwistStamped : RosMessage
			{
				public std_msgs.msg.Header header;
				public geometry_msgs.msg.Twist twist;


				public TwistStamped()
				{
					this.header = new std_msgs.msg.Header();
					this.twist = new geometry_msgs.msg.Twist();
				}

				public TwistStamped(std_msgs.msg.Header header, geometry_msgs.msg.Twist twist)
				{
					this.header = header;
					this.twist = twist;
				}

				new public static string GetMessageType()
				{
					return "geometry_msgs/msg/TwistStamped";
				}

			} // class TwistStamped
		} // namespace msg
	} // namespace geometry_msgs
} // namespace SIGVerse.RosBridge
