// Generated by gencs from geometry_msgs/msg/TwistWithCovariance.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.geometry_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace geometry_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class TwistWithCovariance : RosMessage
			{
				public geometry_msgs.msg.Twist twist;
				public double[]  covariance;


				public TwistWithCovariance()
				{
					this.twist = new geometry_msgs.msg.Twist();
					this.covariance = new double[36];
				}

				public TwistWithCovariance(geometry_msgs.msg.Twist twist, double[]  covariance)
				{
					this.twist = twist;
					this.covariance = covariance;
				}

				new public static string GetMessageType()
				{
					return "geometry_msgs/msg/TwistWithCovariance";
				}

			} // class TwistWithCovariance
		} // namespace msg
	} // namespace geometry_msgs
} // namespace SIGVerse.RosBridge
