// Generated by gencs from geometry_msgs/msg/TwistWithCovarianceStamped.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs.msg;
using SIGVerse.RosBridge.geometry_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace geometry_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class TwistWithCovarianceStamped : RosMessage
			{
				public std_msgs.msg.Header header;
				public geometry_msgs.msg.TwistWithCovariance twist;


				public TwistWithCovarianceStamped()
				{
					this.header = new std_msgs.msg.Header();
					this.twist = new geometry_msgs.msg.TwistWithCovariance();
				}

				public TwistWithCovarianceStamped(std_msgs.msg.Header header, geometry_msgs.msg.TwistWithCovariance twist)
				{
					this.header = header;
					this.twist = twist;
				}

				new public static string GetMessageType()
				{
					return "geometry_msgs/msg/TwistWithCovarianceStamped";
				}

			} // class TwistWithCovarianceStamped
		} // namespace msg
	} // namespace geometry_msgs
} // namespace SIGVerse.RosBridge
