// Generated by gencs from geometry_msgs/msg/Vector3.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace geometry_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class Vector3 : RosMessage
			{
				public double x;
				public double y;
				public double z;


				public Vector3()
				{
					this.x = 0.0;
					this.y = 0.0;
					this.z = 0.0;
				}

				public Vector3(double x, double y, double z)
				{
					this.x = x;
					this.y = y;
					this.z = z;
				}

				new public static string GetMessageType()
				{
					return "geometry_msgs/msg/Vector3";
				}

			} // class Vector3
		} // namespace msg
	} // namespace geometry_msgs
} // namespace SIGVerse.RosBridge
