// Generated by gencs from geometry_msgs/msg/Vector3Stamped.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs.msg;
using SIGVerse.RosBridge.geometry_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace geometry_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class Vector3Stamped : RosMessage
			{
				public std_msgs.msg.Header header;
				public UnityEngine.Vector3 vector;


				public Vector3Stamped()
				{
					this.header = new std_msgs.msg.Header();
					this.vector = new UnityEngine.Vector3();
				}

				public Vector3Stamped(std_msgs.msg.Header header, UnityEngine.Vector3 vector)
				{
					this.header = header;
					this.vector = vector;
				}

				new public static string GetMessageType()
				{
					return "geometry_msgs/msg/Vector3Stamped";
				}

			} // class Vector3Stamped
		} // namespace msg
	} // namespace geometry_msgs
} // namespace SIGVerse.RosBridge
