// Generated by gencs from geometry_msgs/msg/VelocityStamped.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs.msg;
using SIGVerse.RosBridge.geometry_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace geometry_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class VelocityStamped : RosMessage
			{
				public std_msgs.msg.Header header;
				public string body_frame_id;
				public string reference_frame_id;
				public geometry_msgs.msg.Twist velocity;


				public VelocityStamped()
				{
					this.header = new std_msgs.msg.Header();
					this.body_frame_id = "";
					this.reference_frame_id = "";
					this.velocity = new geometry_msgs.msg.Twist();
				}

				public VelocityStamped(std_msgs.msg.Header header, string body_frame_id, string reference_frame_id, geometry_msgs.msg.Twist velocity)
				{
					this.header = header;
					this.body_frame_id = body_frame_id;
					this.reference_frame_id = reference_frame_id;
					this.velocity = velocity;
				}

				new public static string GetMessageType()
				{
					return "geometry_msgs/msg/VelocityStamped";
				}

			} // class VelocityStamped
		} // namespace msg
	} // namespace geometry_msgs
} // namespace SIGVerse.RosBridge
