// Generated by gencs from builtin_interfaces/msg/Time.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace builtin_interfaces 
	{
		namespace msg 
		{
			[System.Serializable]
			public class Time : RosMessage
			{
				public System.Int32 sec;
				public System.UInt32 nanosec;


				public Time()
				{
					this.sec = 0;
					this.nanosec = 0;
				}

				public Time(System.Int32 sec, System.UInt32 nanosec)
				{
					this.sec = sec;
					this.nanosec = nanosec;
				}

				new public static string GetMessageType()
				{
					return "builtin_interfaces/msg/Time";
				}

			} // class Time
		} // namespace msg
	} // namespace builtin_interfaces
} // namespace SIGVerse.RosBridge
