// Generated by gencs from sensor_msgs/JointState.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs;

namespace SIGVerse.RosBridge 
{
	namespace sensor_msgs 
	{
		[System.Serializable]
		public class JointState : RosMessage
		{
			public std_msgs.Header header;
			public System.Collections.Generic.List<string>  name;
			public System.Collections.Generic.List<double>  position;
			public System.Collections.Generic.List<double>  velocity;
			public System.Collections.Generic.List<double>  effort;


			public JointState()
			{
				this.header = new std_msgs.Header();
				this.name = new System.Collections.Generic.List<string>();
				this.position = new System.Collections.Generic.List<double>();
				this.velocity = new System.Collections.Generic.List<double>();
				this.effort = new System.Collections.Generic.List<double>();
			}

			public JointState(std_msgs.Header header, System.Collections.Generic.List<string>  name, System.Collections.Generic.List<double>  position, System.Collections.Generic.List<double>  velocity, System.Collections.Generic.List<double>  effort)
			{
				this.header = header;
				this.name = name;
				this.position = position;
				this.velocity = velocity;
				this.effort = effort;
			}

			new public static string GetMessageType()
			{
				return "sensor_msgs/JointState";
			}

			new public static string GetMD5Hash()
			{
				return "3066dcd76a6cfaef579bd0f34173e9fd";
			}
		} // class JointState
	} // namespace sensor_msgs
} // namespace SIGVerse.ROSBridge

