// Generated by gencs from sensor_msgs/NavSatStatus.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace sensor_msgs 
	{
		[System.Serializable]
		public class NavSatStatus : RosMessage
		{
			public sbyte status;
			public System.UInt16 service;

			public const sbyte STATUS_NO_FIX = -1;
			public const sbyte STATUS_FIX = 0;
			public const sbyte STATUS_SBAS_FIX = 1;
			public const sbyte STATUS_GBAS_FIX = 2;
			public const System.UInt16 SERVICE_GPS = 1;
			public const System.UInt16 SERVICE_GLONASS = 2;
			public const System.UInt16 SERVICE_COMPASS = 4;
			public const System.UInt16 SERVICE_GALILEO = 8;

			public NavSatStatus()
			{
				this.status = 0;
				this.service = 0;
			}

			public NavSatStatus(sbyte status, System.UInt16 service)
			{
				this.status = status;
				this.service = service;
			}

			new public static string GetMessageType()
			{
				return "sensor_msgs/NavSatStatus";
			}

			new public static string GetMD5Hash()
			{
				return "331cdbddfa4bc96ffc3b9ad98900a54c";
			}
		} // class NavSatStatus
	} // namespace sensor_msgs
} // namespace SIGVerse.ROSBridge

