// Generated by gencs from sensor_msgs/PointCloud2.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs;
using SIGVerse.RosBridge.sensor_msgs;

namespace SIGVerse.RosBridge 
{
	namespace sensor_msgs 
	{
		[System.Serializable]
		public class PointCloud2 : RosMessage
		{
			public std_msgs.Header header;
			public System.UInt32 height;
			public System.UInt32 width;
			public System.Collections.Generic.List<sensor_msgs.PointField>  fields;
			public bool is_bigendian;
			public System.UInt32 point_step;
			public System.UInt32 row_step;
			public System.Collections.Generic.List<byte>  data;
			public bool is_dense;


			public PointCloud2()
			{
				this.header = new std_msgs.Header();
				this.height = 0;
				this.width = 0;
				this.fields = new System.Collections.Generic.List<sensor_msgs.PointField>();
				this.is_bigendian = false;
				this.point_step = 0;
				this.row_step = 0;
				this.data = new System.Collections.Generic.List<byte>();
				this.is_dense = false;
			}

			public PointCloud2(std_msgs.Header header, System.UInt32 height, System.UInt32 width, System.Collections.Generic.List<sensor_msgs.PointField>  fields, bool is_bigendian, System.UInt32 point_step, System.UInt32 row_step, System.Collections.Generic.List<byte>  data, bool is_dense)
			{
				this.header = header;
				this.height = height;
				this.width = width;
				this.fields = fields;
				this.is_bigendian = is_bigendian;
				this.point_step = point_step;
				this.row_step = row_step;
				this.data = data;
				this.is_dense = is_dense;
			}

			new public static string GetMessageType()
			{
				return "sensor_msgs/PointCloud2";
			}

			new public static string GetMD5Hash()
			{
				return "1158d486dd51d683ce2f1be655c3c181";
			}
		} // class PointCloud2
	} // namespace sensor_msgs
} // namespace SIGVerse.ROSBridge

