// Generated by gencs from sensor_msgs/RelativeHumidity.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs;

namespace SIGVerse.RosBridge 
{
	namespace sensor_msgs 
	{
		[System.Serializable]
		public class RelativeHumidity : RosMessage
		{
			public std_msgs.Header header;
			public double relative_humidity;
			public double variance;


			public RelativeHumidity()
			{
				this.header = new std_msgs.Header();
				this.relative_humidity = 0.0;
				this.variance = 0.0;
			}

			public RelativeHumidity(std_msgs.Header header, double relative_humidity, double variance)
			{
				this.header = header;
				this.relative_humidity = relative_humidity;
				this.variance = variance;
			}

			new public static string GetMessageType()
			{
				return "sensor_msgs/RelativeHumidity";
			}

			new public static string GetMD5Hash()
			{
				return "8730015b05955b7e992ce29a2678d90f";
			}
		} // class RelativeHumidity
	} // namespace sensor_msgs
} // namespace SIGVerse.ROSBridge

