// Generated by gencs from geometry_msgs/Accel.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.geometry_msgs;

namespace SIGVerse.RosBridge 
{
	namespace geometry_msgs 
	{
		[System.Serializable]
		public class Accel : RosMessage
		{
			public UnityEngine.Vector3 linear;
			public UnityEngine.Vector3 angular;


			public Accel()
			{
				this.linear = new UnityEngine.Vector3();
				this.angular = new UnityEngine.Vector3();
			}

			public Accel(UnityEngine.Vector3 linear, UnityEngine.Vector3 angular)
			{
				this.linear = linear;
				this.angular = angular;
			}

			new public static string GetMessageType()
			{
				return "geometry_msgs/Accel";
			}

			new public static string GetMD5Hash()
			{
				return "9f195f881246fdfa2798d1d3eebca84a";
			}
		} // class Accel
	} // namespace geometry_msgs
} // namespace SIGVerse.ROSBridge

