// Generated by gencs from geometry_msgs/Inertia.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.geometry_msgs;

namespace SIGVerse.RosBridge 
{
	namespace geometry_msgs 
	{
		[System.Serializable]
		public class Inertia : RosMessage
		{
			public double m;
			public UnityEngine.Vector3 com;
			public double ixx;
			public double ixy;
			public double ixz;
			public double iyy;
			public double iyz;
			public double izz;


			public Inertia()
			{
				this.m = 0.0;
				this.com = new UnityEngine.Vector3();
				this.ixx = 0.0;
				this.ixy = 0.0;
				this.ixz = 0.0;
				this.iyy = 0.0;
				this.iyz = 0.0;
				this.izz = 0.0;
			}

			public Inertia(double m, UnityEngine.Vector3 com, double ixx, double ixy, double ixz, double iyy, double iyz, double izz)
			{
				this.m = m;
				this.com = com;
				this.ixx = ixx;
				this.ixy = ixy;
				this.ixz = ixz;
				this.iyy = iyy;
				this.iyz = iyz;
				this.izz = izz;
			}

			new public static string GetMessageType()
			{
				return "geometry_msgs/Inertia";
			}

			new public static string GetMD5Hash()
			{
				return "1d26e4bb6c83ff141c5cf0d883c2b0fe";
			}
		} // class Inertia
	} // namespace geometry_msgs
} // namespace SIGVerse.ROSBridge

