// Generated by gencs from geometry_msgs/Point.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace geometry_msgs 
	{
		[System.Serializable]
		public class Point : RosMessage
		{
			public double x;
			public double y;
			public double z;


			public Point()
			{
				this.x = 0.0;
				this.y = 0.0;
				this.z = 0.0;
			}

			public Point(double x, double y, double z)
			{
				this.x = x;
				this.y = y;
				this.z = z;
			}

			new public static string GetMessageType()
			{
				return "geometry_msgs/Point";
			}

			new public static string GetMD5Hash()
			{
				return "4a842b65f413084dc2b10fb484ea7f17";
			}
		} // class Point
	} // namespace geometry_msgs
} // namespace SIGVerse.ROSBridge

