// Generated by gencs from geometry_msgs/Pose.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.geometry_msgs;

namespace SIGVerse.RosBridge 
{
	namespace geometry_msgs 
	{
		[System.Serializable]
		public class Pose : RosMessage
		{
			public UnityEngine.Vector3 position;
			public UnityEngine.Quaternion orientation;


			public Pose()
			{
				this.position = new UnityEngine.Vector3();
				this.orientation = new UnityEngine.Quaternion();
			}

			public Pose(UnityEngine.Vector3 position, UnityEngine.Quaternion orientation)
			{
				this.position = position;
				this.orientation = orientation;
			}

			new public static string GetMessageType()
			{
				return "geometry_msgs/Pose";
			}

			new public static string GetMD5Hash()
			{
				return "e45d45a5a1ce597b249e23fb30fc871f";
			}
		} // class Pose
	} // namespace geometry_msgs
} // namespace SIGVerse.ROSBridge

