// Generated by gencs from geometry_msgs/TransformStamped.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs;
using SIGVerse.RosBridge.geometry_msgs;

namespace SIGVerse.RosBridge 
{
	namespace geometry_msgs 
	{
		[System.Serializable]
		public class TransformStamped : RosMessage
		{
			public std_msgs.Header header;
			public string child_frame_id;
			public geometry_msgs.Transform transform;


			public TransformStamped()
			{
				this.header = new std_msgs.Header();
				this.child_frame_id = "";
				this.transform = new geometry_msgs.Transform();
			}

			public TransformStamped(std_msgs.Header header, string child_frame_id, geometry_msgs.Transform transform)
			{
				this.header = header;
				this.child_frame_id = child_frame_id;
				this.transform = transform;
			}

			new public static string GetMessageType()
			{
				return "geometry_msgs/TransformStamped";
			}

			new public static string GetMD5Hash()
			{
				return "b5764a33bfeb3588febc2682852579b0";
			}
		} // class TransformStamped
	} // namespace geometry_msgs
} // namespace SIGVerse.ROSBridge

