// Generated by gencs from geometry_msgs/TwistWithCovarianceStamped.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.std_msgs;
using SIGVerse.RosBridge.geometry_msgs;

namespace SIGVerse.RosBridge 
{
	namespace geometry_msgs 
	{
		[System.Serializable]
		public class TwistWithCovarianceStamped : RosMessage
		{
			public std_msgs.Header header;
			public geometry_msgs.TwistWithCovariance twist;


			public TwistWithCovarianceStamped()
			{
				this.header = new std_msgs.Header();
				this.twist = new geometry_msgs.TwistWithCovariance();
			}

			public TwistWithCovarianceStamped(std_msgs.Header header, geometry_msgs.TwistWithCovariance twist)
			{
				this.header = header;
				this.twist = twist;
			}

			new public static string GetMessageType()
			{
				return "geometry_msgs/TwistWithCovarianceStamped";
			}

			new public static string GetMD5Hash()
			{
				return "8927a1a12fb2607ceea095b2dc440a96";
			}
		} // class TwistWithCovarianceStamped
	} // namespace geometry_msgs
} // namespace SIGVerse.ROSBridge

